new feature reservation
jabardigitalservice/reservasi-backend pull request #1
Opened 2021-01-11 06:50 UTC by ayocodingit

overview

cc: @firmanhxc @aldidoanta @rindibudiaramdhan

2021-01-11 07:18 UTC, yohang88 requested changes
Tolong diperbaiki dulu, dan pastikan implementasi sesuai best practice di Laravel ;) 

Contoh yang tidak ada standar-nya, adalah kenapa harus banyak pakai seperti ini:
```
return response()->json(['code' => 200, 'message' => 'success'], 200);
```

2021-01-11 07:18 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +        $models = $models->skip(($page - 1) * $perpage)->take($perpage)->get();
Ini kenapa harus re-invent the wheel bikin fitur pagination sendiri ya? Laravel kan sudah punya method `paginate()`

2021-01-11 07:18 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +        $result = [
Seharusnya pakai standar response Laravel, yaitu pakai API Resource https://laravel.com/docs/8.x/eloquent-resources

2021-01-11 07:18 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +    public function index(Request $request)
Satu method ini terlalu panjang jumlah lines-nya.

2021-01-11 07:18 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +            $params = json_decode($params, true);
Ini $params isinya seperti apa ya? Kenapa harus ada json_decode dan semacamnya?

2021-01-11 07:18 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +                if ($val !== false && ($val == '' || is_array($val) && count($val) == 0)) {
Ini untuk apa kenapa kok ribet sekali?

2021-01-11 07:18 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +        if ($request->user()->role === UserRole::EMPLOYEE()->getValue()) {
Ini komparasi value-nya tidak sesuai dengan contoh dokumentasi enum

2021-01-11 07:18 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +                    $models = $models->orderBy($order, $order_direction);
Ada duplikasi `orderBy`

2021-01-11 07:18 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +                        $models->whereDate('created_at', '>=', Carbon::parse($val)->format('Y-m-d'));
Ini kenapa harus di-parsing? Format atribut datetime bisa dicast di tempat lain?

2021-01-11 07:18 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +        DB::beginTransaction();
Ini untuk apa pakai transaction ya?

2021-01-11 07:18 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +            $reservation->reservation_start = Carbon::parse($request->reservation_start)->format('Y-m-d H:i:s');
Ini `reservation_start` dan `reservation_end` sebaiknya pakai format datetime standar https://wiki.digitalservice.id/doc/api-standard-ZjmiAeN3Qm

2021-01-11 07:18 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +            $asset = Asset::findOrFail($request->asset_id);
Seharusnya ditangani di validasi sebelum masuk ke controller

2021-01-11 07:18 UTC, yohang88 commented on app/Http/Requests/AcceptReservation.php
> +            'approval_status' => "required|in:$already_approved,$rejected",
Ini tidak sesuai best practice di dokumentasi library enum

2021-01-11 07:22 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +            $reservation = new Reservation();
Pelajari best practice mass-assignment https://github.com/alexeymezenin/laravel-best-practices

2021-01-11 07:24 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +    public function accept(AcceptReservation $request, $id)
Bagian ini kebawah, sebaiknya jangan implementasi error message & code tersendiri, karena Laravel sudah bisa handle itu otomatis.

Ingat konsep Don't repeat yourself (DRY) juga https://github.com/alexeymezenin/laravel-best-practices#dont-repeat-yourself-dry

2021-01-11 07:26 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +        try {
Ini terlalu overkill penggunaan try-catch juga, seharusnya ini ga perlu dihandle sendiri sedemikian ;)

2021-01-11 09:13 UTC, ayocodingit commented
siap saya perbaiki dulu mas

2021-01-11 12:03 UTC, rindibudiaramdhan requested changes

2021-01-11 12:03 UTC, rindibudiaramdhan commented on app/Http/Controllers/V1/ReservationController.php
> +        }
proses filter data, kalau dibeginikan hanya akan ada 1 case yang terfilter, padahal tiap $request filterisasi yang dikirim ini harus bisa dikombinasikan juga.

2021-01-11 12:06 UTC, rindibudiaramdhan commented on app/Enums/ReservationStatus.php
> +    }
kenapa pemilihannya ke function, padahal bisa dijadikan constanta seperti aturan ini,
https://github.com/alexeymezenin/laravel-best-practices#use-config-and-language-files-constants-instead-of-text-in-the-code

2021-01-11 12:07 UTC, rindibudiaramdhan commented on app/Enums/UserRole.php
> +    }
kenapa pemilihannya ke function, padahal bisa dijadikan constanta seperti aturan ini,
https://github.com/alexeymezenin/laravel-best-practices#use-config-and-language-files-constants-instead-of-text-in-the-code

2021-01-11 12:35 UTC, rindibudiaramdhan commented on app/Http/Requests/AcceptReservation.php
> +            'approval_status' => "required|in:$already_approved,$rejected",
https://laravel.com/docs/7.x/validation#using-rule-objects

mungkin bisa sebagai acuan

2021-01-11 12:38 UTC, rindibudiaramdhan commented on app/Http/Controllers/V1/ReservationController.php
> +    public function index(Request $request)
coba mungkin artikel ini bisa jadi acuan kang @ayocodingit https://mykeels.medium.com/writing-clean-composable-eloquent-filters-edd242c82cc8

2021-01-11 12:40 UTC, rindibudiaramdhan commented on app/Http/Controllers/V1/ReservationController.php
> +        ]);
https://github.com/alexeymezenin/laravel-best-practices#mass-assignment

bisa jadi acuan utk mass assignment kang @ayocodingit

2021-01-11 12:51 UTC, rindibudiaramdhan commented on database/migrations/2021_01_11_031853_create_reservations_table.php
> +                ->constrained('users')
ini benerkah `asset_id` constrained ke `users`?

2021-01-11 13:01 UTC, rindibudiaramdhan commented on app/Models/Reservation.php
> +    }
ini untuk field yang mana ya?

2021-01-11 13:12 UTC, rindibudiaramdhan commented on routes/api.php
> +});
https://restfulapi.net/resource-naming/ bisa jadi acuan kang @ayocodingit

2021-01-11 13:14 UTC, rindibudiaramdhan commented on app/Http/Controllers/V1/ReservationController.php
> +        $models = $models->skip(($page - 1) * $perpage)->take($perpage)->get();
dokumentasi paginate nya disini ya kang @ayocodingit  https://laravel.com/docs/7.x/pagination

2021-01-11 16:11 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +        ]);
Betul, mass assignment ini bisa mengurangi assignment dari request ke model.

2021-01-11 16:14 UTC, yohang88 commented on app/Http/Requests/AcceptReservation.php
> +            'approval_status' => "required|in:$alreadyApproved,$rejected",
Ini bisa ikuti dokumentasi officialnya https://github.com/spatie/laravel-enum#validation-rule

2021-01-11 16:15 UTC, yohang88 commented on app/Models/Reservation.php
> +    const NOT_YET_APPROVED = 'NOT_YET_APPROVED';
Ini kenapa pakai const di sini ya? Sudah betul sebelumnya pakai Enum package

2021-01-11 16:17 UTC, yohang88 commented on app/Rules/AssetReservation.php
> +        return $reservation ? false : true;
Variabel `$reservation` ini ambigu, kurang jelas naming dan outputnya apa. Fyi Laravel Eloquent memiliki method `exists()` untuk check apakah sebuah query memiliki row atau tidak https://laravel.com/docs/8.x/queries#determining-if-records-exist

2021-01-12 00:48 UTC, ayocodingit commented
Boleh di cross check lagi yah

2021-01-12 10:53 UTC, aldidoanta approved these changes

2021-01-12 14:05 UTC, rindibudiaramdhan approved these changes

2021-01-12 14:07 UTC, merged

2021-01-14 01:57 UTC, yohang88 commented on routes/api.php
> +Route::group(['prefix' => 'reservation', 'namespace' => 'V1'], function () {
Ini kenapa masih belum pakai ResourceController ya?

2021-01-14 01:57 UTC, yohang88 commented on app/Models/Reservation.php
> +    public function getSomeDateAttribute($date)
Ini untuk apa ya?

2021-01-14 01:59 UTC, yohang88 commented on app/Models/Reservation.php
> +    protected $dates = [
Atribut `created_at`, `updated_at`, `deleted_at` itu udah otomatis di-cast sebagai `date`, tidak perlu dideklarasi ulang.

2021-01-14 01:59 UTC, yohang88 commented on app/Models/Reservation.php
> +        'asset_name',
Ini kenapa ada aset name ya? bukannya ini relasional?