Sebagai Pegawai, saya dapat membuat reservasi baru
jabardigitalservice/reservasi-backend pull request #10
Opened 2021-01-16 10:16 UTC by rindibudiaramdhan

- [ ] Harus mengisi Judul Kegiatan
- [ ] Harus memilih Aset/Resource yang akan direservasi
- [ ] Aset/Resource yang bisa dipilih hanya yang statusnya Aktif saja
- [ ] Dapat menambahkan Catatan Kegiatan jika diperlukan
- [ ] Bisa melihat jadwal/info kapan aset/resource available untuk direservasi
- [ ] Harus mengisi Jadwal Reservasi, dengan cara memilih tanggal; rentang waktu mulai dan selesai
- [ ] Tidak bisa overlapping jika aset/resource sudah pernah dibooking pada rentang waktu yang dipilih

2021-01-16 16:09 UTC, yohang88 commented
Ini strategi git-nya gimana ya? Kenapa ada `development`, ada `staging` ?

2021-01-16 16:09 UTC, yohang88 requested changes
Ini strategi git-nya gimana ya? Kenapa ada development, ada staging ?

2021-01-17 00:14 UTC, rindibudiaramdhan commented
> Ini strategi git-nya gimana ya? Kenapa ada `development`, ada `staging` ?

Maaf mas @yohang88 kalau dari segi penamaan branchnya membingungkan. Saya akan coba menjelaskan masing-masing branch tersebut.

1. Branch `development`
digunakan untuk tim _backend_ fokus di fiturnya terlebih dahulu dengan cara:

- menghasilkan berbagai opsi _problem solving_ fitur
- diujicobakan ke _frontend_ untuk menghasilkan _feedback_ opsi yang terbaik
- _Bug Fixing_.
- kemudian dilakukan _code review_ untuk di _merge_ ke `staging`

2. Branch `staging`
digunakan QA dalam pengujian fitur sebelum di _merge_ ke `production`

🙏

2021-01-19 01:44 UTC, rindibudiaramdhan commented
untuk git flow ini sudah saya sesuaikan dengan yang teman2 biasa lakukan. mohon maaf jika membuat bingung. 🙏

2021-01-19 06:21 UTC, aldidoanta commented
Kang @rindibudiaramdhan , changes di PR ini dipakai di PR-PR berikutnya ya?
Kala gitu, fokus review-nya di sini dulu ya kang.

2021-01-19 06:24 UTC, aldidoanta commented on app/Exceptions/Handler.php
> +            //return self::response_error($e->getMessage(), 500);
Yang ini masih dipakai kah kang? Boleh dihapus ya kalau sudah tidak dipakai

2021-01-19 06:30 UTC, rindibudiaramdhan commented on app/Exceptions/Handler.php
> +            //return self::response_error($e->getMessage(), 500);
siap kang @aldidoanta . saya hapus dahulu

2021-01-19 07:14 UTC, aldidoanta approved these changes

2021-01-19 07:16 UTC, aldidoanta commented
Oiya, untuk setiap PR, tmn2 backend reservasi yg lain sebaiknya ikut review juga ya. Tujuannya supaya bisa tahu progress fitur yg dibuat oleh temannya yg lain. Tmn2 bisa respon dengan ikut approve, comment, atau sekedar kasih like di PR ini.

Kang @ayocodingit @rachadiannovansyah CMIIW

2021-01-19 07:17 UTC, aldidoanta commented
> > Ini strategi git-nya gimana ya? Kenapa ada `development`, ada `staging` ?
> 
> Maaf mas @yohang88 kalau dari segi penamaan branchnya membingungkan. Saya akan coba menjelaskan masing-masing branch tersebut.
> 
> 1. Branch `development`
>    digunakan untuk tim _backend_ fokus di fiturnya terlebih dahulu dengan cara:
> 
> * menghasilkan berbagai opsi _problem solving_ fitur
> * diujicobakan ke _frontend_ untuk menghasilkan _feedback_ opsi yang terbaik
> * _Bug Fixing_.
> * kemudian dilakukan _code review_ untuk di _merge_ ke `staging`
> 
> 1. Branch `staging`
>    digunakan QA dalam pengujian fitur sebelum di _merge_ ke `production`

Untuk penamaan branch, berarti sudah beres ya kang @rindibudiaramdhan ?

2021-01-19 07:24 UTC, rachadiannovansyah approved these changes

2021-01-19 07:39 UTC, rindibudiaramdhan commented
untuk penamaan branch sudah aman kang. untuk staging kita menggunakan branch `dev`. untuk production kita menggunakan branch `master`

2021-01-19 07:40 UTC, merged