Feature repeated bookings
jabardigitalservice/reservasi-backend pull request #116
Opened 2021-04-16 06:57 UTC by samudra-ajri

Add daily booking feature

    User can create daily reservations with multiple days
    User can create daily reservation for a year only
    User cannot create passed day reservation
    Daily reservation request will fail if there has another reservation at the same day and time
    Daily reservation request will fail if there has no reservation occurrences

Trello: https://trello.com/c/cuVWKobl

@jabardigitalservice/jds-backend

2021-04-19 01:53 UTC, ayocodingit commented on app/Http/Controllers/V1/ReservationDailyController.php
> +            while ($date->lte($end_date)) {
kang @samudra-ajri kalau $date->lte itu apa yah ?

2021-04-19 01:53 UTC, ayocodingit commented on app/Http/Controllers/V1/ReservationDailyController.php
> +        $asset = Asset::find($request->asset_id);
ini bisa gunakan findOrFail gak yah jika asset null

2021-04-19 01:57 UTC, yohang88 requested changes
Fyi umumnya fitur booking/reservasi berulang itu disebut `Recurring` 😁 Sehingga akan lebih mudah dipahami jika naming things-nya berkaitan dengan recurring daily.

2021-04-19 01:57 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationDailyController.php
> +        $reservationCreated = 0;
ini penulisan variable tidak konsisten 😁 Sebaiknya dibuat konsisten `snakeCase` untuk variable 😁

2021-04-19 01:57 UTC, yohang88 commented on app/Http/Requests/ReservationRepeatRequest.php
> +        $max_date = Carbon::now('+07:00')->addYear()->format('Y-m-d');
Ini kenapa harus ada +7 ? Seharusnya dari frontend sudah dikirim dalam bentuk timezone UTC, sehingga backend dan frontend konsisten bertukar data dalam timezone UTC.

Kasusnya adalah jika ada pegawai yang booking di timezone selain WIB (+7), misal WITA (+8), pasti jadi invalid 😁

2021-04-19 01:57 UTC, yohang88 commented on resources/lang/en/message.php
> +    'no_reservation' => 'No reservatoin occurrences',
Typo `reservatoin`

2021-04-19 01:57 UTC, yohang88 commented on resources/lang/id/message.php
> +    'no_reservation' => 'Tidak ada reservasi yang terjadi',
`Tidak ada reservasi yang terjadi` ini maksudnya apa ya? 😁

2021-04-19 02:10 UTC, samudra-ajri commented on app/Http/Controllers/V1/ReservationDailyController.php
> +            while ($date->lte($end_date)) {
Buat ngecek $date kurang date $end_date, Kang

2021-04-19 02:12 UTC, samudra-ajri commented on app/Http/Controllers/V1/ReservationDailyController.php
> +        $asset = Asset::find($request->asset_id);
Bisa juga, Kang..
Selain di validasi exist di form request, method yg dipanggil pakai findOrFail ya, Kang?

2021-04-19 02:16 UTC, samudra-ajri commented on resources/lang/en/message.php
> +    'no_reservation' => 'No reservatoin occurrences',
Wah, siap, Mas.. :grin:

2021-04-19 02:32 UTC, samudra-ajri commented on resources/lang/id/message.php
> +    'no_reservation' => 'Tidak ada reservasi yang terjadi',
sederhananya translate dari `No reservatiin occurrences`, Mas.. :grin: 
Kejadiannya ketika hari yg ingin direservasi tidak ada di dalam range rencana reservasi.

Spertinya lebih baik dibuat menjadi `Tidak ada reservasi yang dibuat` ya, Mas?

2021-04-19 02:37 UTC, samudra-ajri commented on app/Http/Controllers/V1/ReservationDailyController.php
> +        $reservationCreated = 0;
Siap, Mas.. Kebawa2 sama nama field db-nya, hhe..
Hatur nuhun, Mas..

2021-04-19 02:47 UTC, samudra-ajri commented
> Fyi umumnya fitur booking/reservasi berulang itu disebut `Recurring` grin Sehingga akan lebih mudah dipahami jika naming things-nya berkaitan dengan recurring daily.

Contohnya seperti `ReservationDailyController` menjadi `ReservationDailyRecurringController` betul begitu, Mas?

2021-04-19 03:24 UTC, ayocodingit commented on app/Http/Controllers/V1/ReservationDailyController.php
> +        $asset = Asset::find($request->asset_id);
kalau udh pake validasi exist gak usah menggunakan findOrFail kang
sip gunakan find aja

2021-04-19 03:36 UTC, ayocodingit approved these changes

2021-04-19 03:44 UTC, samudra-ajri commented on app/Http/Requests/ReservationRepeatRequest.php
> +        $max_date = Carbon::now('+07:00')->addYear()->format('Y-m-d');
Siap, Mas.. Sudah diperbaiki

Hatur nuhun, Mas..

e5f8485

2021-04-20 00:44 UTC, yohang88 commented on resources/lang/id/message.php
> +    'no_reservation' => 'Tidak ada reservasi yang terjadi',
yup dengan gitu kayaknya lebih mudah dipahami 😁

2021-04-20 00:47 UTC, yohang88 commented
> > Fyi umumnya fitur booking/reservasi berulang itu disebut `Recurring` grin Sehingga akan lebih mudah dipahami jika naming things-nya berkaitan dengan recurring daily.
> 
> Contohnya seperti `ReservationDailyController` menjadi `ReservationDailyRecurringController` betul begitu, Mas?

Iyes bisa gitu, nampaknya lebih clear namingnya 😁 

Btw 1 lagi aku ketinggalan kemarin, kalau bisa ditambahkan API/HTTP testing ya untuk fitur yang ini 😁

2021-04-20 00:50 UTC, samudra-ajri commented
> > > Fyi umumnya fitur booking/reservasi berulang itu disebut `Recurring` grin Sehingga akan lebih mudah dipahami jika naming things-nya berkaitan dengan recurring daily.
> > 
> > 
> > Contohnya seperti `ReservationDailyController` menjadi `ReservationDailyRecurringController` betul begitu, Mas?
> 
> Iyes bisa gitu, nampaknya lebih clear namingnya grin
> 
> Btw 1 lagi aku ketinggalan kemarin, kalau bisa ditambahkan API/HTTP testing ya untuk fitur yang ini grin

Siap, Mas.. 86..
Hatur nuhun, Mas :pray:

2021-04-22 08:03 UTC, yohang88 approved these changes

2021-04-22 08:04 UTC, merged