Feature reservation multiple asset
jabardigitalservice/reservasi-backend pull request #117
Opened 2021-04-19 05:57 UTC by iprasetyaa

# Overview

Melakukan penambahan reservasi dengan multiple asset dalam waktu bersamaan
Memperbaiki email template yang disesuaikan dengan multilple asset
Memperbaiki unit test store reservation

CC : @jabardigitalservice/jds-backend

2021-04-20 01:07 UTC, ayocodingit commented
Kang @iprasetyaa boleh di pelajari menggunakan queue biar tidak menurunkan performa 😁

2021-04-20 01:09 UTC, iprasetyaa commented
> Kang @iprasetyaa boleh di pelajari menggunakan queue biar tidak menurunkan performa 😁

Coba saya update dulu pake queue, di saat kirim email nya berarti ya kang? @ayocodingit

2021-04-20 01:09 UTC, firmanhxc commented on app/Http/Requests/CreateReservationRequest.php
> +        $date = Carbon::now('+07:00')->subDay()->format('Y-m-d');
@iprasetyaa ini kemaren baru ada review sejenis deh, coba cek https://github.com/jabardigitalservice/reservasi-backend/pull/116#discussion_r615498913

2021-04-20 01:13 UTC, iprasetyaa commented on app/Http/Requests/CreateReservationRequest.php
> +        $date = Carbon::now('+07:00')->subDay()->format('Y-m-d');
okey kang saya sesuaikan dulu hatur nuhun kang @firmanhxc  🙏

2021-04-20 01:14 UTC, firmanhxc requested changes

2021-04-20 01:14 UTC, firmanhxc commented on app/Rules/CreateAssetReservationRule.php
> +    public function __construct($ids, $date, $start_time, $end_time)
untuk variable baiknya dibuat snakeCase jadi $startTime $endTime, referensi : https://www.laravelbestpractices.com/#variables

2021-04-20 01:30 UTC, ayocodingit commented
> > Kang @iprasetyaa boleh di pelajari menggunakan queue biar tidak menurunkan performa 😁
> 
> Coba saya update dulu pake queue, di saat kirim email nya berarti ya kang? @ayocodingit 
> 

Betul kang

2021-04-20 02:55 UTC, iprasetyaa commented on app/Http/Requests/CreateReservationRequest.php
> +        $date = Carbon::now('+07:00')->subDay()->format('Y-m-d');
kang, sudah sudah di fix ae1948b

2021-04-20 03:22 UTC, iprasetyaa commented on app/Rules/CreateAssetReservationRule.php
> +    public function __construct($ids, $date, $start_time, $end_time)
sudah diupdate dengan camelCase kang @firmanhxc

2021-04-20 05:43 UTC, iprasetyaa commented
> > > Kang @iprasetyaa boleh di pelajari menggunakan queue biar tidak menurunkan performa 😁
> > 
> > 
> > Coba saya update dulu pake queue, di saat kirim email nya berarti ya kang? @ayocodingit
> 
> Betul kang

kang in sudah saya buat send emailnya dengan queue @ayocodingit

2021-04-20 05:46 UTC, ayocodingit commented
> > > > Kang @iprasetyaa boleh di pelajari menggunakan queue biar tidak menurunkan performa 😁
> > > 
> > > 
> > > Coba saya update dulu pake queue, di saat kirim email nya berarti ya kang? @ayocodingit
> > 
> > Betul kang
> 
> kang in sudah saya buat send emailnya dengan queue @ayocodingit 

Sudah coba di local blm kang 
Run workernya

2021-04-20 05:47 UTC, iprasetyaa commented
> > > > > Kang @iprasetyaa boleh di pelajari menggunakan queue biar tidak menurunkan performa 😁
> > > > 
> > > > 
> > > > Coba saya update dulu pake queue, di saat kirim email nya berarti ya kang? @ayocodingit
> > > 
> > > 
> > > Betul kang
> > 
> > 
> > kang in sudah saya buat send emailnya dengan queue @ayocodingit
> 
> Sudah coba di local blm kang
> Run workernya

saya run pake `php artisan queue:work` jalan kang

2021-04-20 05:54 UTC, ayocodingit commented
> > > > > > Kang @iprasetyaa boleh di pelajari menggunakan queue biar tidak menurunkan performa 😁
> > > > > 
> > > > > 
> > > > > Coba saya update dulu pake queue, di saat kirim email nya berarti ya kang? @ayocodingit
> > > > 
> > > > 
> > > > Betul kang
> > > 
> > > 
> > > kang in sudah saya buat send emailnya dengan queue @ayocodingit
> > 
> > Sudah coba di local blm kang
> > Run workernya
> 
> saya run pake `php artisan queue:work` jalan kang

Berarti tinggal implementasi di server nya kang @iprasetyaa buat container terpisah untuk run php artisan queue:work

2021-04-20 06:01 UTC, iprasetyaa commented
> > > > > > > Kang @iprasetyaa boleh di pelajari menggunakan queue biar tidak menurunkan performa 😁
> > > > > > 
> > > > > > 
> > > > > > Coba saya update dulu pake queue, di saat kirim email nya berarti ya kang? @ayocodingit
> > > > > 
> > > > > 
> > > > > Betul kang
> > > > 
> > > > 
> > > > kang in sudah saya buat send emailnya dengan queue @ayocodingit
> > > 
> > > 
> > > Sudah coba di local blm kang
> > > Run workernya
> > 
> > 
> > saya run pake `php artisan queue:work` jalan kang
> 
> Berarti tinggal implementasi di server nya kang @iprasetyaa buat container terpisah untuk run php artisan queue:work
> Boleh di bantu devOps yah

Oke kang @ayocodingit coba tanya ke DevOps dulu untuk setup di server

2021-04-20 06:08 UTC, ayocodingit commented
> > > > > > > > Kang @iprasetyaa boleh di pelajari menggunakan queue biar tidak menurunkan performa 😁
> > > > > > > 
> > > > > > > 
> > > > > > > Coba saya update dulu pake queue, di saat kirim email nya berarti ya kang? @ayocodingit
> > > > > > 
> > > > > > 
> > > > > > Betul kang
> > > > > 
> > > > > 
> > > > > kang in sudah saya buat send emailnya dengan queue @ayocodingit
> > > > 
> > > > 
> > > > Sudah coba di local blm kang
> > > > Run workernya
> > > 
> > > 
> > > saya run pake `php artisan queue:work` jalan kang
> > 
> > Berarti tinggal implementasi di server nya kang @iprasetyaa buat container terpisah untuk run php artisan queue:work
> > Boleh di bantu devOps yah
> 
> Oke kang @ayocodingit coba tanya ke DevOps dulu untuk setup di server.
> Nuhun masukannya kang 🙏😁

Up di slack yah kang @iprasetyaa biar tau issue worker ini hehe

2021-04-20 06:14 UTC, iprasetyaa commented
> > > > > > > > > Kang @iprasetyaa boleh di pelajari menggunakan queue biar tidak menurunkan performa 😁
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Coba saya update dulu pake queue, di saat kirim email nya berarti ya kang? @ayocodingit
> > > > > > > 
> > > > > > > 
> > > > > > > Betul kang
> > > > > > 
> > > > > > 
> > > > > > kang in sudah saya buat send emailnya dengan queue @ayocodingit
> > > > > 
> > > > > 
> > > > > Sudah coba di local blm kang
> > > > > Run workernya
> > > > 
> > > > 
> > > > saya run pake `php artisan queue:work` jalan kang
> > > 
> > > 
> > > Berarti tinggal implementasi di server nya kang @iprasetyaa buat container terpisah untuk run php artisan queue:work
> > > Boleh di bantu devOps yah
> > 
> > 
> > Oke kang @ayocodingit coba tanya ke DevOps dulu untuk setup di server.
> > Nuhun masukannya kang 🙏😁
> 
> Up di slack yah kang @iprasetyaa biar tau issue worker ini hehe 😁

siap kang gasssss 🙌

2021-04-20 07:02 UTC, ayocodingit approved these changes

2021-04-20 07:03 UTC, ayocodingit commented
Paling nunggu worker nya running yah kang @iprasetyaa

2021-04-20 07:04 UTC, iprasetyaa commented
> Paling nunggu worker nya running yah kang @iprasetyaa

Iya kang, btw dari sisi BE perlu disiapkan apa aja kang? @ayocodingit

2021-04-20 07:08 UTC, ayocodingit commented
> > Paling nunggu worker nya running yah kang @iprasetyaa
> 
> Iya kang, btw dari sisi BE perlu disiapkan apa aja kang? @ayocodingit 

Tinggal sisi servernya aja kang @iprasetyaa

2021-04-20 07:10 UTC, iprasetyaa commented
> > > Paling nunggu worker nya running yah kang @iprasetyaa
> > 
> > 
> > Iya kang, btw dari sisi BE perlu disiapkan apa aja kang? @ayocodingit
> 
> Tinggal sisi servernya aja kang @iprasetyaa

oke kang mantap mantap

2021-04-20 08:36 UTC, firmanhxc approved these changes

2021-04-21 08:49 UTC, azophy approved these changes

2021-04-21 09:21 UTC, yohang88 requested changes
Mangstaaaap mantuls @iprasetyaa @samudra-ajri @ayocodingit 🎉 

Cek cek minor dikit 😁

2021-04-21 09:21 UTC, yohang88 commented on Dockerfile
> +HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8080/fpm-ping
Btw ini memang health check-nya jalan saat dijalankan mode queue worker? Soalnya kan ga jalankan nginx & php-fpm? Saat dijalankan `docker ps` outputnya seperti apa ya status container processnya?

2021-04-21 09:21 UTC, yohang88 commented on resources/views/emails/reservationApproval.blade.php
> +- Tanggal Dibuat: {{ $data[0]['reservation']->created_at->format('d-m-Y') }}
Ini kenapa harus getter pakai index `$data[0]` ya? Kenapa dari controller ga dilempar 1 instance/model aja, jadi ga perlu diakses pakai index array.

2021-04-22 00:57 UTC, iprasetyaa commented on captain-definition-worker
> + }
done deleted mas @yohang88

2021-04-22 00:59 UTC, iprasetyaa commented on Dockerfile
> +HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8080/fpm-ping
ini kemarin buat test di local mas, masih nyangkut kebawa, harusnya gakebawa mas @yohang88 😅
done deleted

2021-04-22 01:02 UTC, iprasetyaa commented on resources/views/emails/reservationApproval.blade.php
> +- Tanggal Dibuat: {{ $data[0]['reservation']->created_at->format('d-m-Y') }}
saya mikirnya biar tidak get lagi ke model, biar sekalian 1 data aja soalnya untuk booking multiple asset ini kan datanya sebenarnya sama aja per bookingnya. 

apa baiknya saya get lagi 1 data dari model untuk a?gar tidak menggunakan index array [0] mas?

2021-04-22 08:02 UTC, yohang88 approved these changes

2021-04-22 08:03 UTC, merged