Sebagai Pegawai, saya dapat mengubah reservasi yang baru dibuat selama statusnya belum disetujui oleh Admin FO
jabardigitalservice/reservasi-backend pull request #14
Opened 2021-01-17 00:28 UTC by rindibudiaramdhan

Acceptance Criteria
- [ ] Judul Kegiatan bisa diubah
- [ ] Catatan Kegiatan bisa diubah
- [ ] Aset/Resource bisa diubah
- [ ] Aset/Resource yang bisa dipilih hanya yang statusnya Aktif saja
- [ ] Tanggal dan Waktu kegiatan bisa diubah
- [ ] Pegawai hanya bisa mengubah jika statusnya belum disetujui/ditolak oleh Admin FO
- [ ] Tidak bisa overlapping jika aset/resource sudah pernah dibooking pada rentang waktu yang dipilih
- [ ] [Trello](https://trello.com/c/Y1XWPgcS/4-sebagai-pegawai-saya-dapat-mengubah-reservasi-yang-baru-dibuat-selama-statusnya-belum-disetujui-oleh-admin-fo)

2021-01-19 03:22 UTC, sandisunandar99 commented on app/Exceptions/Handler.php
> +            //return self::response_error($e->getMessage(), 500);
mang kayanya kalo dokumentasi kaya gini bgusnya mah di simpen di atas func aja. cmiwwiw :smile:

2021-01-19 03:57 UTC, rindibudiaramdhan commented on app/Exceptions/Handler.php
> +            //return self::response_error($e->getMessage(), 500);
siap kang @sandisunandar99 otw dipindahkan

2021-01-19 04:22 UTC, sandisunandar99 approved these changes

2021-01-19 15:10 UTC, aldidoanta commented
Related https://github.com/jabardigitalservice/reservasi-backend/pull/12

Saya akan review lagi ya kalau branch `dev` sudah update dengan PR di atas

2021-01-19 15:14 UTC, aldidoanta requested changes

2021-01-19 15:14 UTC, aldidoanta commented on app/Rules/UpdateAssetReservationRule.php
> +            ->where($attribute, $value)->first();
minor kang @rindibudiaramdhan , yang `->first()` kayaknya lebih baik ditaruh di baris berikutnya. CMIIW
```suggestion
            ->where($attribute, $value)
            ->first();
```

2021-01-20 06:31 UTC, rindibudiaramdhan commented on app/Rules/UpdateAssetReservationRule.php
> +            ->where($attribute, $value)->first();
baik kang @aldidoanta

2021-01-20 06:37 UTC, rindibudiaramdhan commented
> Related #12
> 
> Saya akan review lagi ya kalau branch `dev` sudah update dengan PR di atas

sudah di merge dari `dev` kang @aldidoanta . dan perbaikan catatan minor juga sudah diselesaikan 🙏

2021-01-20 12:03 UTC, aldidoanta commented on app/Http/Controllers/V1/ReservationController.php
> +        $reservation = $reservation->update([
Kang @rindibudiaramdhan mau tanya. Kalau lihat di [Reservation class](https://github.com/jabardigitalservice/reservasi-backend/blob/dev/app/Models/Reservation.php#L12), kan udah ada variabel `$fillable` ya. Nama-nama field yang ada di `$fillable` ini bisa dipakai untuk mass assignment.

Misalnya spt ini
```php
public function update(UpdateReservationRequest $request, Reservation $reservation)
{
    ...
    $reservation->fill($request->all())->save();
    ...
}
```
https://stackoverflow.com/a/54976932/7414531

2021-01-20 12:04 UTC, aldidoanta commented on app/Http/Controllers/V1/ReservationController.php
> +        $reservation = $reservation->update([
Oh tapi ada field yang namanya beda ya kang, yg  `'user_id_updated' => $user->id,`

Sipsip, nanti kalau ada kebutuhan update yang field-nya sama persis, boleh dicoba ya kang

2021-01-20 12:05 UTC, aldidoanta approved these changes

2021-01-20 12:06 UTC, aldidoanta commented
Kang @rachadiannovansyah @ayocodingit  besok boleh review PR ini juga ya :pray:

2021-01-20 12:46 UTC, ayocodingit approved these changes

2021-01-20 13:19 UTC, merged