Optimize recurring zoom
jabardigitalservice/reservasi-backend pull request #154
Opened 2021-05-07 07:00 UTC by iprasetyaa

# Overview

1.  Optimize zoom recurring using create zoom create meetings recurrence API
2.  Adjust mail template for recurring reservation

2021-05-07 08:02 UTC, samudra-ajri approved these changes

2021-05-10 05:21 UTC, ayocodingit requested changes

2021-05-10 05:21 UTC, ayocodingit commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        return optional($getLastReservation)->recurring_id + 1 ?? 1;
ini sifatnya harus unique yah kang @iprasetyaa

2021-05-10 05:21 UTC, ayocodingit commented on app/Listeners/CreateZoomMeetingRecurring.php
> +            $reservation = Reservation::findOrFail($item);
ini kalau Fail akan langsung gagal 404 kang @iprasetyaa sebaiknya gunakan where aja biar return nya null dan program tidak error 404

2021-05-10 05:21 UTC, ayocodingit commented on app/Listeners/CreateZoomMeetingRecurring.php
> +        $daysTotal          = count((array)$request->days);
ini kenapa harus di convert dulu ke array yah

2021-05-10 05:21 UTC, ayocodingit commented on app/Listeners/CreateZoomMeetingRecurring.php
> +                    'type' => 2,
type ini boleh dibuat enum kang @iprasetyaa

2021-05-10 05:35 UTC, iprasetyaa commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        return optional($getLastReservation)->recurring_id + 1 ?? 1;
yup unique kang, baiknya dibuat gimana ya kang?

2021-05-10 05:37 UTC, iprasetyaa commented on app/Listeners/CreateZoomMeetingRecurring.php
> +                    'type' => 2,
itu type dari rule nya zoom sih kang untuk keperluan bookuing, bukan type dimasukin ke db

2021-05-10 05:40 UTC, iprasetyaa commented on app/Listeners/CreateZoomMeetingRecurring.php
> +        $daysTotal          = count((array)$request->days);
eh iya si request->days dia dalam bentuk array, nuhun kang remindernya

2021-05-10 05:54 UTC, ayocodingit commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        return optional($getLastReservation)->recurring_id + 1 ?? 1;
Di cek dulu menggunakan do while jika masih ada trus di tambah satu

2021-05-10 05:57 UTC, ayocodingit commented on app/Listeners/CreateZoomMeetingRecurring.php
> +                    'type' => 2,
Iya walau buat zoom sebaiknya type nya dibuat enum biar paham type 1 itu apa dsb 😁

2021-05-10 06:06 UTC, iprasetyaa commented on app/Listeners/CreateZoomMeetingRecurring.php
> +                    'type' => 2,
oke kang siap siap saya fix dulu

2021-05-10 06:29 UTC, iprasetyaa commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        return optional($getLastReservation)->recurring_id + 1 ?? 1;
kalau ambil last id gitu terus di + 1, kekurangannya gimana kang?

2021-05-10 06:54 UTC, ayocodingit commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        return optional($getLastReservation)->recurring_id + 1 ?? 1;
Kalau di hit barengan akan duplicate kang

2021-05-10 08:24 UTC, rindibudiaramdhan commented
btw yang ini mau naik prod jg kah? soalnya saya lihat ada PR up to production nih. yang PR lain juga apakah seperti itu?

2021-05-11 00:48 UTC, iprasetyaa commented
> btw yang ini mau naik prod jg kah? soalnya saya lihat ada PR up to production nih. yang PR lain juga apakah seperti itu?

ini belum up ke prod kang @rindibudiaramdhan

2021-05-17 06:40 UTC, iprasetyaa commented on app/Listeners/CreateZoomMeetingRecurring.php
> +            $reservation = Reservation::findOrFail($item);
sudah di update kang @ayocodingit

2021-05-17 06:40 UTC, iprasetyaa commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        return optional($getLastReservation)->recurring_id + 1 ?? 1;
sudah di update kang @ayocodingit

2021-05-17 06:40 UTC, iprasetyaa commented on app/Listeners/CreateZoomMeetingRecurring.php
> +                    'type' => 2,
sudah di update kang @ayocodingit

2021-05-17 07:26 UTC, ayocodingit approved these changes

2021-05-17 07:27 UTC, rachadiannovansyah approved these changes

2021-05-17 07:35 UTC, merged