add recurring reservation delete functionality
jabardigitalservice/reservasi-backend pull request #172
Opened 2021-05-19 03:11 UTC by samudra-ajri

Add function to delete all records by recurring_id.

@jabardigitalservice/jds-backend

2021-05-19 03:35 UTC, ayocodingit requested changes

2021-05-19 03:35 UTC, ayocodingit commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        Reservation::where('recurring_id', $reservation->recurring_id)->delete();
ini bisa seperti ini gak yah kang @samudra-ajri 
```suggestion
        $reservation->delete();
```

2021-05-19 03:49 UTC, samudra-ajri commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        Reservation::where('recurring_id', $reservation->recurring_id)->delete();
Punten, Kang @ayocodingit 
Pas saya coba pakai cara tsb hanya delete records pertama saja, Kang.

2021-05-19 03:54 UTC, ayocodingit commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        Reservation::where('recurring_id', $reservation->recurring_id)->delete();
oh tujuannya bisa multiple reccuring id yang sama yah kang @samudra-ajri 
berarti untuk kasus ini tidak perlu menggunakan route model binding

2021-05-19 03:56 UTC, samudra-ajri commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        Reservation::where('recurring_id', $reservation->recurring_id)->delete();
Siap, Kang.. :+1:

2021-05-19 04:22 UTC, samudra-ajri commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        Reservation::where('recurring_id', $reservation->recurring_id)->delete();
Punten, Kang @ayocodingit 
Klw dia ngga pakai model binding kena `authorizeResource`.

2021-05-19 04:26 UTC, samudra-ajri commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        Reservation::where('recurring_id', $reservation->recurring_id)->delete();
kecuali klw `public function __construct()
    {
        $this->authorizeResource(Reservation::class);
    }` kita hapus

2021-05-19 04:41 UTC, ayocodingit commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        Reservation::where('recurring_id', $reservation->recurring_id)->delete();
oalah kena authorizeResource yah 
berarti boleh gunakan teknik model observer kang tapi di taro di model aja contoh nya
![image](https://user-images.githubusercontent.com/41193120/118757309-0c3f9c80-b897-11eb-8a18-92ca51024671.png)
agar tetap single responsibility principle :smile:

2021-05-19 05:42 UTC, samudra-ajri commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        Reservation::where('recurring_id', $reservation->recurring_id)->delete();
Hum, saya kira maksud dari _single responsibility principle_ lebih ke prilaku dan objek yg berada dalam satu class saja, Kang? Misalkan priakunya khusus untuk crud saja, atau misalkan khusus untuk menghandel objek user saja. Sedangkan teknis dibebaskan.

Gitu bukan ya, Kang?
cmiiw

2021-05-19 05:57 UTC, ayocodingit commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        Reservation::where('recurring_id', $reservation->recurring_id)->delete();
jadi simple nya mah satu fungsi satu goal :smile:

2021-05-19 06:09 UTC, samudra-ajri commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        Reservation::where('recurring_id', $reservation->recurring_id)->delete();
Hho.. mantap, siap, Kang..

2021-05-19 07:32 UTC, samudra-ajri commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        Reservation::where('recurring_id', $reservation->recurring_id)->delete();
Punten, Kang @ayocodingit 
Klw dari dokumentasi `authorizeResource` ini dipakai ketika controller berupa resource controller. Karena controller ini bukan resource controller, apakah sebaiknya `authorizeResource` dihapus saja, Kan?

https://laravel.com/docs/8.x/authorization

2021-05-19 07:35 UTC, ayocodingit commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        Reservation::where('recurring_id', $reservation->recurring_id)->delete();
Iya kang hapus aja kalau bukan authorized resource tapi gunakan authorized tapi jika dibutuhkan 😁

2021-05-19 07:53 UTC, samudra-ajri commented on app/Http/Controllers/V1/ReservationRecurringController.php
> +        Reservation::where('recurring_id', $reservation->recurring_id)->delete();
Siap, Kang.. 86..
Hatur nuhun, Kang

2021-05-19 08:07 UTC, ayocodingit approved these changes

2021-05-20 02:21 UTC, rachadiannovansyah approved these changes

2021-05-21 02:17 UTC, merged