Aset resource management
jabardigitalservice/reservasi-backend pull request #2
Opened 2021-01-11 22:59 UTC by rachadiannovansyah

In this branch include :
- endpoint to Create, Read, Update and Delete from aset management
- also add endpoint to search name & status based on query string

Note:
- try to implement best practice laravel from https://github.com/alexeymezenin/laravel-best-practices#contents

please to review my code akang2
@yohang88 
@rindibudiaramdhan 
@ayocodingit 

hatur nuhun

2021-01-12 03:06 UTC, yohang88 requested changes
Minta tolong diperbaiki dulu:

1. Start clean, ikuti best practice dari dokumentasi Laravel. Kita kurangi programmer A bikin gaya penulisan A, programmer B gaya penulisan B. Yang paling aman adalah mengikuti dokumentasi Laravel.

2. Belum mengikuti coding style PSR-12 https://www.php-fig.org/psr/psr-12/

3. Pelajari penerapan clean code di repo API Tes Masif https://github.com/jabardigitalservice/pikobar-rapidtest-api/tree/master/app/Http/Controllers/Rdt

2021-01-12 03:06 UTC, yohang88 commented on app/Http/Controllers/AsetResourceController.php
> +    public function getById($id) {
Belum sesuai coding convention https://www.php-fig.org/psr/psr-12/

2021-01-12 03:06 UTC, yohang88 commented on app/Http/Requests/StoreAsetRequest.php
> +            'status' => 'required|in:aktif,tidak aktif',
Gunakan Enum https://github.com/spatie/laravel-enum

2021-01-12 03:06 UTC, yohang88 commented on app/Http/Requests/StoreAsetRequest.php
> +    protected function failedValidation(Validator $validator)
Ini untuk apa ya? bukannya Laravel by default udah handle ini

2021-01-12 03:06 UTC, yohang88 commented on config/app.php
> +    'timezone' => 'Asia/Bangkok',
Timezone server aplikasi harus dalam UTC

2021-01-12 03:06 UTC, yohang88 commented on database/migrations/2021_01_11_023940_create_aset_resources_table.php
> +            $table->enum('status', ['aktif', 'tidak aktif']);
gunakan standar bahasa inggris

2021-01-12 04:19 UTC, rachadiannovansyah commented on app/Http/Requests/StoreAsetRequest.php
> +    protected function failedValidation(Validator $validator)
ini untuk handle error message dari FormRequest (php artisan:make request) mas..

2021-01-12 14:13 UTC, rindibudiaramdhan requested changes
kang novan, dirapihkan dulu penamaan asetnya di tiap `class`, `method` dan `parameter`nya ya. `aset` menjadi `asset` kang.

2021-01-12 22:15 UTC, rachadiannovansyah commented
> kang novan, dirapihkan dulu penamaan asetnya di tiap `class`, `method` dan `parameter`nya ya. `aset` menjadi `asset` kang.

2021-01-12 22:16 UTC, rachadiannovansyah commented
> kang novan, dirapihkan dulu penamaan asetnya di tiap `class`, `method` dan `parameter`nya ya. `aset` menjadi `asset` kang.

2021-01-12 22:22 UTC, rachadiannovansyah commented
siap sudah kang @rindibudiaramdhan

2021-01-12 23:49 UTC, rindibudiaramdhan commented on app/Asset.php
> +}
kang @rachadiannovansyah, class softDelete nya belum kepasang kayaknya.
fitur deletenya akan delete record nanti kang

disini kang contekannya ya https://laravel.com/docs/7.x/eloquent#soft-deleting 👍

2021-01-12 23:54 UTC, rindibudiaramdhan commented on app/Asset.php
> +}
termasuk yang class migrasinya ya kang. karena ada requirement kalau asetnya dihapus data aset yang pernah direservasi tidak hilang. https://trello.com/c/hiCWrYeQ/13-sebagai-admin-fo-saya-dapat-menghapus-resource-dan-aset-yang-sudah-ada

walaupun fitur hapus ini hanya ada di product backlog 👍

2021-01-13 00:55 UTC, rachadiannovansyah commented on app/Asset.php
> +}
sudah dipush final codenya, mangga di review kang

2021-01-13 00:59 UTC, rachadiannovansyah commented on app/Http/Requests/StoreAsetRequest.php
> +    protected function failedValidation(Validator $validator)
ooo ini sudah diremove mas, kurang headers ternyata :smile:

2021-01-13 01:25 UTC, rindibudiaramdhan commented on app/Http/Controllers/AssetController.php
> +        $perPage = $this->getPaginationSize($perPage);
`$perPage = $this->getPaginationSize($perPage);` berarti sudah tidak diperlukan ya kang @rachadiannovansyah ?

btw code untuk filternya dimana ya? 🙏

2021-01-13 01:46 UTC, rindibudiaramdhan approved these changes

2021-01-13 04:04 UTC, sandisunandar99 commented
kang @rachadiannovansyah mungkin ini mah sedit saran aja moga berguna,, :+1:  bsa pake editorconfig supaya lebih rapi kaya spacing tab nya,,
bisa di lihat di bawah ya cara pake nya,, 
nuhun
`https://editorconfig.org/`

2021-01-13 05:11 UTC, rachadiannovansyah commented
> kang @rachadiannovansyah mungkin ini mah sedit saran aja moga berguna,,  bsa pake editorconfig supaya lebih rapi kaya spacing tab nya,,
> bisa di lihat di bawah ya cara pake nya,,
> nuhun
> `https://editorconfig.org/`

siap kang hatur nuhun

2021-01-13 05:38 UTC, rachadiannovansyah commented
> Minta tolong diperbaiki dulu:
> 
> 1. Start clean, ikuti best practice dari dokumentasi Laravel. Kita kurangi programmer A bikin gaya penulisan A, programmer B gaya penulisan B. Yang paling aman adalah mengikuti dokumentasi Laravel.
> 2. Belum mengikuti coding style PSR-12 https://www.php-fig.org/psr/psr-12/
> 3. Pelajari penerapan clean code di repo API Tes Masif https://github.com/jabardigitalservice/pikobar-rapidtest-api/tree/master/app/Http/Controllers/Rdt

sudah diperbaiki berdasarkan kriteria diatas mas

2021-01-13 05:48 UTC, yohang88 requested changes
Semangat, sedikit lagi 😁 @rachadiannovansyah

2021-01-13 05:48 UTC, yohang88 commented on routes/api.php
> +Route::prefix('asset')->group(function() {
Laravel memiliki best practice route dan controller untuk REST API, dari naming route, method, sampai controllernya, ikutin ya 😁 https://laravel.com/docs/8.x/controllers#api-resource-routes

2021-01-13 05:48 UTC, yohang88 commented on database/migrations/2021_01_13_004844_create_assets_table.php
> +            $table->enum('status', ['active', 'not_active']);
ini tidak konsisten dengan value di AssetStatusEnum

2021-01-13 05:48 UTC, yohang88 commented on app/Http/Controllers/AssetController.php
> +    protected function searchList(Request $request, $records)
Seharusnya fungsional search itu ada di endpoint yang sama dengan list utama

2021-01-13 05:49 UTC, yohang88 commented on routes/api.php
> +Route::prefix('asset')->group(function () {
Laravel memiliki best practice route dan controller untuk REST API, dari naming route, method, sampai controllernya, ikutin ya 😁 https://laravel.com/docs/8.x/controllers#api-resource-routes

2021-01-13 07:37 UTC, rachadiannovansyah commented on routes/api.php
> +Route::prefix('asset')->group(function () {
> Semangat, sedikit lagi  @rachadiannovansyah

siappp sdh diperbaiki mas yoga :+1:

2021-01-13 07:44 UTC, yohang88 commented on database/migrations/2021_01_13_004844_create_assets_table.php
> +        Schema::table('assets', function (Blueprint $table) {
Ini kenapa harus dipisah ya?

2021-01-13 07:46 UTC, yohang88 commented on routes/api.php
> +Route::resource('asset', 'AssetController')->except(['edit', 'create']);
Kenapa harus pakai `except()` ? Dokumentasi Laravel ada juga `apiResource()` https://laravel.com/docs/8.x/controllers#api-resource-routes 😉

2021-01-13 07:46 UTC, yohang88 commented on routes/api.php
> +Route::get('/asset-available-list', 'AssetController@activeList');
Ini untuk apa ya? Kenapa endpointnya beda juga?

2021-01-13 07:49 UTC, rachadiannovansyah commented on routes/api.php
> +Route::resource('asset', 'AssetController')->except(['edit', 'create']);
ini udah mas di commitan terakhir

2021-01-13 07:50 UTC, rachadiannovansyah commented on routes/api.php
> +Route::get('/asset-available-list', 'AssetController@activeList');
oo itu yg dibawah function diluar resource mas

2021-01-13 07:52 UTC, rachadiannovansyah commented on database/migrations/2021_01_13_004844_create_assets_table.php
> +        Schema::table('assets', function (Blueprint $table) {
ini untuk handle php artisan migrate:rollback mas, karna aku klo bikin migration selalu nyoba ngerollback utk ngecek migration nya udah bener ato belumm :))

2021-01-13 08:15 UTC, yohang88 commented on database/migrations/2021_01_13_004844_create_assets_table.php
> +        Schema::table('assets', function (Blueprint $table) {
@rachadiannovansyah maksud saya, kenapa `dropSoftDeletes()` dan `Schema::dropIfExists()` dipisah?

2021-01-13 08:16 UTC, yohang88 commented on routes/api.php
> +Route::get('/asset-available-list', 'AssetController@activeList');
@rachadiannovansyah Kalau memang fungsionalnya diluar resource REST, sebaiknya dipisahkan Controllernya yang lebih sesuai fungsinya. Path endpointnya dikelompokkan di `/asset/*` juga saja.

2021-01-13 08:23 UTC, rachadiannovansyah commented on database/migrations/2021_01_13_004844_create_assets_table.php
> +        Schema::table('assets', function (Blueprint $table) {
oooiya bisa disatukan, sudah direfactor mas

2021-01-13 08:56 UTC, rachadiannovansyah commented on routes/api.php
> +Route::get('/asset-available-list', 'AssetController@activeList');
ooo oke 1 controller 1 fungsi yaa (single responsibility),
udah diperbaiki, boleh dicek lagi mas wkwk

2021-01-13 10:55 UTC, ayocodingit approved these changes

2021-01-13 10:59 UTC, merged

2021-01-14 01:44 UTC, yohang88 commented on app/Http/Controllers/ListController.php
> +class ListController extends Controller
Naming `ListController` ini terlalu umum. List apa? 😬