Bugfix validasi reservation
jabardigitalservice/reservasi-backend pull request #20
Opened 2021-01-21 10:31 UTC by ayocodingit

overview 

bugfix validasi reservation (waktu booking)

cc @jabardigitalservice/jds-backend @rachadiannovansyah

2021-01-21 11:04 UTC, rachadiannovansyah approved these changes

2021-01-21 15:28 UTC, aldidoanta commented on app/Rules/StoreAssetReservationRule.php
> +                $record->orWhereTime('start_time', '>', $start_time->addSecond(1))
kang @ayocodingit , kalo boleh tau, knp harus pakai `addSecond(1)`?

2021-01-21 18:32 UTC, yohang88 requested changes
Cek cek sedikit

2021-01-21 18:32 UTC, yohang88 commented on app/Rules/StoreAssetReservationRule.php
> +                    ->WhereTime('end_time', '<', $end_time)->subSeconds(1);
Ini sama ya, kenapa harus pakai `subSeconds(1)` ?

2021-01-21 18:32 UTC, yohang88 commented on app/Rules/UpdateAssetReservationRule.php
>          return $result && $result->id !== $this->id ? false : true;
Ini susah dibaca, terlalu panjang kondisionalnya, dan sebenarnya apa tujuan baris ini? 😁

2021-01-22 17:56 UTC, ayocodingit commented on app/Rules/StoreAssetReservationRule.php
> +                $record->orWhereTime('start_time', '>', $start_time->addSecond(1))
sudah di perbaiki

2021-01-22 18:00 UTC, rindibudiaramdhan approved these changes

2021-01-22 18:01 UTC, ayocodingit commented on app/Rules/StoreAssetReservationRule.php
> +                    ->WhereTime('end_time', '<', $end_time)->subSeconds(1);
udh di update mas

2021-01-22 18:01 UTC, ayocodingit commented on app/Rules/UpdateAssetReservationRule.php
>          return $result && $result->id !== $this->id ? false : true;
udh di update mas

2021-01-22 18:01 UTC, ayocodingit commented
> Cek cek sedikit

sudah di update

2021-01-24 15:14 UTC, aldidoanta approved these changes

2021-01-25 01:48 UTC, yohang88 commented on app/Models/Reservation.php
> +    public static function convertTimeToDecimal($time)
ini method untuk apa ya?

2021-01-25 04:57 UTC, yohang88 requested changes
Cek cek minor hehe @rindibudiaramdhan @rachadiannovansyah @ayocodingit

2021-01-25 04:57 UTC, yohang88 commented on app/Models/Reservation.php
> +    public const VALIDATION_RULES = [
Btw saya ga rekomendasikan validasi disimpan di level model ya; karena best practice clean-architecture, validasi model itu dilakukan di layer paling luar (request form).

2021-01-25 04:57 UTC, yohang88 commented on app/Models/Reservation.php
> +    public function scopeActionUpdated($query, $id)
ini `action updated` hanya dipakai di 1 tempat kan? sebaiknya tidak perlu dibuat query scope

2021-01-25 04:57 UTC, yohang88 commented on app/Models/Reservation.php
> +    public function notYetApproved()
ini query scope?

2021-01-25 04:57 UTC, yohang88 commented on app/Http/Controllers/V1/DashboardController.php
> +        $result['not_yet_approved'] = Reservation::checkRoleEmployee()
Kalau dibuat seperti ini bisa ga ya?

```
public function scopeByUser($query, $user) 
{
    return $query->where('user_id_reservation', $user->uuid);
}
```
```
$record = new Reservation::query();

if ($request->user->role == UserRoleEnum::employee_reservasi()) {
    $record->byUser($request->user);
    $record->approved();
}

$result['not_yet_approved'] = $record->count();
```

Lebih mudah dibaca dan dipahami yang mana?

2021-01-25 05:12 UTC, ayocodingit commented on app/Models/Reservation.php
> +    public const VALIDATION_RULES = [
![image](https://user-images.githubusercontent.com/41193120/105664145-8d4cdf80-5f06-11eb-9587-cc0fb042337a.png)
Kalau gini gimana mas ?

2021-01-25 05:22 UTC, ayocodingit commented on app/Models/Reservation.php
> +    public function notYetApproved()
bukan mas ini udh cek untuk yang bisa di update atau delete hanya status nya not yet approved

2021-01-25 05:22 UTC, ayocodingit commented on app/Models/Reservation.php
> +    public function scopeActionUpdated($query, $id)
siap udh di perbarui

2021-01-25 06:12 UTC, ayocodingit commented
cek cek lagi yah mas @yohang88

2021-01-25 06:35 UTC, yohang88 approved these changes

2021-01-25 06:37 UTC, merged