Riset phpunit laravel
jabardigitalservice/reservasi-backend pull request #25
Opened 2021-01-27 01:22 UTC by rachadiannovansyah

Trying to implement php unit on mini project to up coverage test of application

![Screenshot from 2021-01-27 08-17-53](https://user-images.githubusercontent.com/32012588/105928382-73330e80-6078-11eb-8f28-8fd695aff3ad.png)

Overview :
- phpunit (./vendor/bin/phpunit) saya tuangkan ke composer object `scripts` sehingga untuk mencoba menjalankan unit test hanya dengan perintah `composer test`
- i also generate file report of coverage html (using XDEBUG)
- use faker for factory
- use seeder for generate data master

Note:
-menggunakan `Illuminate\Foundation\Testing\WithoutMiddleware` (untuk by pass auth keycloak :dancers: )

cc: @jabardigitalservice/jds-backend @yohang88 @rindibudiaramdhan @ayocodingit

2021-01-27 01:48 UTC, yohang88 requested changes
Superb, @rachadiannovansyah ! Outstanding pisan kalau bisa mulai implementasi unit test dan API test 😁 Nanti next stepnya di-run automation pakai CI/CD (Jenkins), cakep pisan 👍 Nais lagi ini udah ditambahkan custom script `composer test` untuk shortcut 👍 

Apalagi kalau bisa TDD 😛 Kita belajar bareng-bareng yuk 😁 

Btw overall test case-nya udah cukup, namun akan lebih baik kalau selain melakukan assertion terhadap response status code, ditambahkan juga assertion terhadap structure response JSON-nya juga 😁 

Btw yang backend pendaftaran tes masif bisa dijadikan referensi baca-baca https://github.com/jabardigitalservice/pikobar-rapidtest-api/tree/master/tests/Feature

2021-01-27 01:48 UTC, yohang88 commented on database/seeds/AssetSeeder.php
> +        \DB::table('assets')->insert(array (
Ini sudah ada Factory untuk Asset, kenapa ga dimanfaatkan di seeder? 😛

2021-01-27 01:48 UTC, yohang88 commented on database/seeds/DatabaseSeeder.php
> +        \DB::table('assets')->delete();
Kapan kita pakai `delete()`, kapan kita pakai `truncante()` ?

2021-01-27 01:48 UTC, yohang88 commented on database/seeds/UserSeeder.php
> +        \DB::table('users')->insert(array (
Ini juga sama, tanggung kalau ga pakai factory untuk User sekalian 😛

2021-01-27 01:48 UTC, yohang88 commented on tests/Feature/AssetTest.php
> +        $this->user = User::find(1);
User ID `1` ini riskan jika hardcode pakai ID gini. Sometimes saat aplikasi udah tambah besar, user testingnya makin banyak, ID `1` ini jadi susah dilacak 😁 Maka saran saya, pakai cara create user baru (bisa pakai Factory) di setiap test case.

2021-01-27 02:01 UTC, rachadiannovansyah commented
> Superb, @rachadiannovansyah ! Outstanding pisan kalau bisa mulai implementasi unit test dan API test  Nanti next stepnya di-run automation pakai CI/CD (Jenkins), cakep pisan  Nais lagi ini udah ditambahkan custom script `composer test` untuk shortcut 
> 
> Apalagi kalau bisa TDD  Kita belajar bareng-bareng yuk 
> 
> Btw overall test case-nya udah cukup, namun akan lebih baik kalau selain melakukan assertion terhadap response status code, ditambahkan juga assertion terhadap structure response JSON-nya juga 
> 
> Btw yang backend pendaftaran tes masif bisa dijadikan referensi baca-baca https://github.com/jabardigitalservice/pikobar-rapidtest-api/tree/master/tests/Feature

Oo i see, siapp mas @yohang88 meluncur :rocket:

2021-01-28 12:50 UTC, rachadiannovansyah commented
![Screenshot from 2021-01-28 19-36-37](https://user-images.githubusercontent.com/32012588/106139830-83dea400-61a0-11eb-8da2-8053819a38cf.png)

Done all controller tested using phpunit (feature test)

Whats new :
- All Coverage 78%++ ( kalo kemaren 87% itu hanya yg controller asset saja )
- Refactor code (sesuai yg mas Yoga arahkan terkait penggunaan factory pada seeder dan php code sniffet)
- Menghilangkan hardcoded find data pada setUp test (menjadi factory disetiap function)

Note:
-Ada beberapa function yang tidak ke hit karna sulit di test terkait function di controller (Reservation) yg menggunakan abort_if (:dancers: )
perlu riset lagi cara mocking function tsb atau function di controller nya di ubah menjadi function if biasa :dancing_men: 

selebihnya sudah diimplementasikan berdasarkan hasil riset phpunit yang saya lakukan

cc: mas @yohang88 @jabardigitalservice/jds-backend

2021-01-28 12:50 UTC, rachadiannovansyah commented on database/seeds/AssetSeeder.php
> +        \DB::table('assets')->insert(array (
done mas updatean terbaru hehe :smiley:

2021-01-28 12:58 UTC, rachadiannovansyah commented on database/seeds/DatabaseSeeder.php
> +        \DB::table('assets')->delete();
setauku delete untuk menghapus langsung row dari tabel tersebut , sedangkan truncate menghapus sementara tabel tersebut sampe benar2 kehapus jika ada data baru yang mengisi tabel tersebut. CMIIW :man_dancing:

2021-01-29 06:01 UTC, yohang88 approved these changes

2021-01-29 10:27 UTC, ayocodingit approved these changes

2021-01-29 11:00 UTC, rindibudiaramdhan approved these changes
mantul riset mengenai Unit Testnya. Share share ya ilmunya kang @rachadiannovansyah

2021-01-29 11:02 UTC, merged