add  validasi revervation update
jabardigitalservice/reservasi-backend pull request #26
Opened 2021-02-01 09:34 UTC by ayocodingit

[overview]

- Tidak bisa edit reservasi jika melebihi waktu maksimal edit **(30menit)**

cc @jabardigitalservice/jds-backend @rachadiannovansyah @rindibudiaramdhan

2021-02-01 11:37 UTC, aldidoanta commented
Hmm awalnya saya bingung akan use case ini, karena biasanya reservasi tidak boleh di-edit jika waktu saat ini kurang dari 30 menit dari waktu yang sudah dijanjikan.

Misalnya saya udah booking jam 19.00, dan sekarang jam 18.36. Harusnya saya udah nggak boleh edit lagi reservasinya. Karena edit reservasi harus dilakukan paling lambat jam 18.30.

Tapi untuk PR ini, use case-nya beda ya?

2021-02-01 12:10 UTC, ayocodingit commented
> Hmm awalnya saya bingung akan use case ini, karena biasanya reservasi tidak boleh di-edit jika waktu saat ini kurang dari 30 menit dari waktu yang sudah dijanjikan.
> 
> Misalnya saya udah booking jam 19.00, dan sekarang jam 18.36. Harusnya saya udah nggak boleh edit lagi reservasinya. Karena edit reservasi harus dilakukan paling lambat jam 18.30.
> 
> Tapi untuk PR ini, use case-nya beda ya?

iya mksdnya gitu kang maaf kata katanya ribet

2021-02-01 12:33 UTC, rindibudiaramdhan commented
> Hmm awalnya saya bingung akan use case ini, karena biasanya reservasi tidak boleh di-edit jika waktu saat ini kurang dari 30 menit dari waktu yang sudah dijanjikan.
> 
> Misalnya saya udah booking jam 19.00, dan sekarang jam 18.36. Harusnya saya udah nggak boleh edit lagi reservasinya. Karena edit reservasi harus dilakukan paling lambat jam 18.30.
> 
> Tapi untuk PR ini, use case-nya beda ya?

Ya, betul sekali kang @aldidoanta. Use case di PR ini maksudnya seperti yang akang sampaikan.
Untuk di fitur reservasinya sebelumnya belum ada validasi ini, makanya sekarang ditambahkan validasi ini.

2021-02-01 13:20 UTC, rindibudiaramdhan commented on app/Http/Controllers/V1/ReservationController.php
> +        abort_if($reservation->start_time->subMinutes(30) > Carbon::now(), 500, __('validation.asset_modified_time'));
`Carbon::now()` masih UTC ya? sedangkan `$reservation->start_time` WIB (UTC+7)
antara yg start_time dibuat UTC atau buat variable penampung yg UTC jadi UTC+7 dulu ya.

2021-02-01 13:52 UTC, rindibudiaramdhan approved these changes

2021-02-01 16:06 UTC, aldidoanta requested changes

2021-02-01 16:06 UTC, aldidoanta commented on resources/lang/id/validation.php
>      'asset_modified' => 'data reservasi dapat di modif jika statusnya belum disetujui',
Minor kang. Kalau di key `asset_modified`, redaksinya kan 
```
... data reservasi dapat di modif ...
```

Sedangkan di line berikutnya, di key `asset_modified_time`, redaksinya
```
... data reservasi tidak dapat diedit ...
```

Sebaiknya pilih satu istilah aja kang, apakah mau pakai istilah **modif** atau **edit**. Kalau saya pribadi lebih pilih **edit**.

2021-02-01 16:06 UTC, aldidoanta commented on app/Http/Controllers/V1/ReservationController.php
> +        abort_if($reservation->start_time->subMinutes(30) > Carbon::now('+07:00'), 500, __('validation.asset_modified_time'));
Di comment di atas kan sudah clear ya, use case-nya seperti apa.

Kalau begitu, logic di line 91 seharusnya seperti ini bukan?
```suggestion
        abort_if(Carbon::now('+07:00') > $reservation->start_time->subMinutes(30), 500, __('validation.asset_modified_time'));
```

2021-02-01 16:34 UTC, ayocodingit commented on app/Http/Controllers/V1/ReservationController.php
> +        abort_if($reservation->start_time->subMinutes(30) > Carbon::now('+07:00'), 500, __('validation.asset_modified_time'));
Betul kang ke balik operator nya harus abort if mencari nilai false 👍

2021-02-01 16:35 UTC, ayocodingit commented on resources/lang/id/validation.php
>      'asset_modified' => 'data reservasi dapat di modif jika statusnya belum disetujui',
Siap kang nuhun

2021-02-02 03:24 UTC, aldidoanta approved these changes

2021-02-02 03:25 UTC, merged