validasi update delete reservasi
jabardigitalservice/reservasi-backend pull request #41
Opened 2021-02-21 06:25 UTC by ayocodingit

### overview

pengecekan validasi saat update
pengecekan validasi saat delete

cc: @jabardigitalservice/jds-backend @yohang88

2021-02-21 18:17 UTC, aldidoanta approved these changes

2021-02-21 18:19 UTC, aldidoanta commented on tests/Feature/ReservationTest.php
> -        $this->withoutExceptionHandling();
Dua line yang dihapus ini, dihapus karena ada perubahan letak `abort_if` ya? Apakah mungkin kalau assertion-nya dipindah ke poin 3 (Verify and Assertion)?

2021-02-22 02:07 UTC, rachadiannovansyah approved these changes

2021-02-22 02:14 UTC, rachadiannovansyah commented on tests/Feature/ReservationTest.php
> -        $this->withoutExceptionHandling();
sepertinya iya kang karna `abort_if` nya dihapus, maksud dari kode ini juga sebenernya dulu untuk handling `abort_if` itu.. nah coba di taro di point 3 trus run lgi test nya kang @ayocodingit :grin:

2021-02-22 03:04 UTC, yohang88 requested changes
Tolong diperbaiki kembali 😁

2021-02-22 03:04 UTC, yohang88 commented on app/Policies/ReservationPolicy.php
> +        abort_if($reservation->check_time_edit_valid, 500, __('validation.asset_modified_time'));
@ayocodingit @rachadiannovansyah Sebenarnya ini kan bagian dari validasi data juga kan?
- Reservasi statusnya belum disetujui
- Reservasi waktunya valid

Karena bagian dari validasi, maka ini lebih tepat masuk ke Form Request, dan bisa dibuat `Rule` tersendiri. Sehingga tidak perlu memaksa sistem `abort`. Dengan membuat Rule validasi sendiri, maka responsenya juga akan sesuai yaitu gagal validasi (Error code 422). Kode error 500 tidak digunakan untuk error validasi 😁

2021-02-22 03:04 UTC, yohang88 commented on app/Policies/ReservationPolicy.php
> +        abort_if($reservation->is_not_yet_approved, 500, __('validation.asset_modified'));
Sama dengan `update()` di atas yes 😁

2021-02-22 03:07 UTC, ayocodingit commented on app/Policies/ReservationPolicy.php
> +        abort_if($reservation->is_not_yet_approved, 500, __('validation.asset_modified'));
kalau pas delete gimana mas ? karena kan gak ada Form Request

2021-02-22 11:09 UTC, ayocodingit commented on app/Policies/ReservationPolicy.php
> +        abort_if($reservation->is_not_yet_approved, 500, __('validation.asset_modified'));
up  mas @yohang88

2021-02-22 11:13 UTC, ayocodingit commented on tests/Feature/ReservationTest.php
> -        $this->withoutExceptionHandling();
![image](https://user-images.githubusercontent.com/41193120/108700700-95199700-7539-11eb-8b6f-2528261c94c9.png)
error kang @aldidoanta

2021-02-22 12:08 UTC, aldidoanta commented on tests/Feature/ReservationTest.php
> -        $this->withoutExceptionHandling();
Kalau lihat kodingannya, function `testDestroyReservation()` dibuat untuk mengetes delete secara normal (positive case) ya? Kalau gitu, line yang di atas memang tidak perlu.

Tapi untuk unit test, sebaiknya ada test case yang menangani negative case. Misalnya kalau mau delete, tapi kena validation error. Kode yang ` $this->expectException()` bisa dipakai untuk memastikan jenis exception yang keluar.

2021-02-22 12:09 UTC, aldidoanta commented on tests/Feature/ReservationTest.php
> -        $this->withoutExceptionHandling();
Tapi bebas ya, apakah mau tambah unit test di PR ini atau nggak.

2021-02-22 12:12 UTC, ayocodingit commented on tests/Feature/ReservationTest.php
> -        $this->withoutExceptionHandling();
kalau untuk

2021-02-22 12:16 UTC, rizkyrmsyah commented on tests/Feature/ReservationTest.php
> -        $this->withoutExceptionHandling();
Kalau di flow yg baru (tanpa approval) unit test nya jadi ada error

2021-02-22 12:16 UTC, rizkyrmsyah commented on tests/Feature/ReservationTest.php
> -        $this->withoutExceptionHandling();
Di bagian sini nya $this->expectException('Symfony\Component\HttpKernel\Exception\HttpException');

2021-02-22 12:52 UTC, ayocodingit commented on tests/Feature/ReservationTest.php
> -        $this->withoutExceptionHandling();
itu bukan karena $this->expectException('Symfony\Component\HttpKernel\Exception\HttpException'); 
tapi salah manggil rule sama perbaikan logic

2021-02-23 01:42 UTC, rindibudiaramdhan commented on app/Policies/ReservationPolicy.php
> +        abort_if($reservation->is_not_yet_approved, 500, __('validation.asset_modified'));
saya prefer status codenya 422karena "Unprocessable Entity", pak @ayocodingit 
mungkin bisa jadi bacaan disini https://dikaseba.blogspot.com/2019/05/rest-http-status-codes-for-failed.html

kita diskusi yak

2021-02-23 02:02 UTC, rindibudiaramdhan approved these changes

2021-02-23 03:12 UTC, yohang88 commented on app/Policies/ReservationPolicy.php
> +        abort_if($reservation->is_not_yet_approved, 500, __('validation.asset_modified'));
@ayocodingit Delete bisa dibuat Form Request juga ga ya? 😁

2021-02-23 05:04 UTC, closed without merging

2021-02-23 06:07 UTC, ayocodingit commented on app/Policies/ReservationPolicy.php
> +        abort_if($reservation->is_not_yet_approved, 500, __('validation.asset_modified'));
Aku coba dia hanya bisa authentication response nya 403 bukan 422