Zoom integrate
jabardigitalservice/reservasi-backend pull request #45
Opened 2021-02-23 04:44 UTC by setiadijoe

- add created zoom meeting and send by email
- TODO:
-- using event listener for create zoom meeting
-- update email body

2021-02-23 10:09 UTC, rindibudiaramdhan commented on .env.example
> +ZOOM_CLIENT_EMAIL=
ini kalau mau single host aja ya. kalau ada multiple host user, bisa diset dimasing-masing assetnya

2021-02-23 10:10 UTC, rindibudiaramdhan commented on app/Http/Controllers/V1/ZoomController.php
> +class ZoomController extends Controller
controller ini gpp kalau ga di push juga. untuk catatan belajar aja ttg perintah2 basic di library laravel-zoom

2021-02-23 10:15 UTC, rindibudiaramdhan commented on app/Observers/ReservationObserver.php
>      }
ini jadi perhatian di develop selanjutnya ya. karena ada trigger update ketika update link zoom, sehingga function `updated` ini jadi ketrigger.

apakah line code disini mau dipakai khusus untuk endpoint edit reservasi saja atau secara keseluruhan perubahan reservasi ditrigger.

2021-02-23 10:17 UTC, rindibudiaramdhan commented on database/factories/AssetFactory.php
> +        'resource_type' => 'online',
bisa pakai function `randomElement` buat kedepannya jika ingin campuran nilai antara `online` atau `offline`

2021-02-23 10:19 UTC, rindibudiaramdhan commented on database/migrations/2021_02_21_224312_add_join_url_to_reservations_table.php
> +            //
nitip tambah `dropColumn('join_url');` disini ya.

2021-02-23 10:33 UTC, rindibudiaramdhan commented on database/migrations/2021_02_22_093057_alter-table-assets-add-secret-key-client-key.php
> +            $table->string('zoom_secret_key')->after('zoom_client_key')->nullable();
ini kayaknya ga perlu ya @setiadijoe @rizkyrmsyah ?

email saja cukup kan?

2021-02-23 10:35 UTC, rindibudiaramdhan reviewed
sip tinggal ditest lanjut lagi yak

2021-02-24 01:43 UTC, setiadijoe commented on database/migrations/2021_02_22_093057_alter-table-assets-add-secret-key-client-key.php
> +            $table->string('zoom_secret_key')->after('zoom_client_key')->nullable();
hmm mksdnya penamaannya jadi cukup `email` aja gak perlu namanya `zoom_email`?

2021-02-24 01:46 UTC, setiadijoe commented
> sip tinggal ditest lanjut lagi yak

sebetulnya ada caranya gak sih untuk ngemock satu fungsi di laravel? kan ini errornya di bagian createMeeting(), yang mana itu teh akses ke Zoom API, kira-kira referensinya ada gak yang kang @rindibudiaramdhan ?

2021-02-24 03:13 UTC, setiadijoe commented
fixed #42

2021-02-24 03:26 UTC, rachadiannovansyah approved these changes

2021-02-24 03:39 UTC, yohang88 requested changes
Gas gas minor dari saya yes, semangat @setiadijoe @rindibudiaramdhan @rachadiannovansyah @rizkyrmsyah @ayocodingit 👍 😁

2021-02-24 03:39 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +            event(new ReservationEmail($reservation));
@setiadijoe Ini sudah bagus, menggunakan konsep Event & Listener 😁 👍 👏 

Tapi akan lebih pas lagi, kalau dibuat sesuai dari konsep 1 Event, punya banyak Listener (Actions).

Contoh kalau di Laravel, studi kasusnya https://laravel.com/docs/8.x/events#registering-events-and-listeners
```php
protected $listen = [
    OrderShipped::class => [
        SendShipmentNotification::class,
    ],
];
```

Maka untuk case create reservasi ini, mungkin bisa dibuat seperti ini:
```php
protected $listen = [
    ReservationCreated::class => [
        SendReservationEmail::class,
        CreateZoomSchedule::class,
    ],
];
```
Namun perlu diperhatikan nanti di dalam Listener `CreateZoomSchedule` harus dilakukan check `resource_type`-nya 😁 

Jadi nanti jika ada kebutuhan lain (aksi lain saat create reservasi), maka hanya perlu menambahkan Listener baru 😁 

cc: @ayocodingit @rindibudiaramdhan @rachadiannovansyah @rizkyrmsyah

2021-02-24 03:39 UTC, yohang88 commented on app/Listeners/SendReservationEmail.php
> +        Mail::to(auth()->user()->email)->send(new ReservationApprovalMail($reservation));
Ini dikirim ke user yang membuat reservasi atau ke user yang sedang login?

Seharusnya kan ke user yang membuat reservasi ya? 😁 

*terlepas dari flow-nya auto approve ya.

2021-02-24 03:39 UTC, yohang88 commented on app/Observers/ReservationObserver.php
> +        // $reservations = Reservation::where('asset_id', $reservation->asset_id)
Hapus aja jika sudah ga dipakai, nanti kan Git bisa lihat history jika dibutuhkan 😁

2021-02-24 03:40 UTC, ayocodingit approved these changes

2021-02-24 03:41 UTC, setiadijoe commented on app/Observers/ReservationObserver.php
> +        // $reservations = Reservation::where('asset_id', $reservation->asset_id)
siap mas, sebentar

2021-02-24 03:49 UTC, rizkyrmsyah commented on app/Listeners/SendReservationEmail.php
> +        Mail::to(auth()->user()->email)->send(new ReservationApprovalMail($reservation));
oh ya kebalik mas :D

2021-02-24 04:21 UTC, setiadijoe commented on app/Http/Controllers/V1/ReservationController.php
> +            event(new ReservationEmail($reservation));
klo yang ini mas @yohang88 , kenapa ada dua event karena memang ada dua event jadi kirim email itu selain di bagian storeReservation ada juga di bagian update Reservation jadi perlu dua event mas. CMIIW

2021-02-24 04:22 UTC, yohang88 commented on app/Listeners/SendReservationEmail.php
> +        Mail::to(auth()->user()->email)->send(new ReservationApprovalMail($reservation));
@rizkyrmsyah Kita mendesain sebuah aplikasi tentu bukan untuk saat ini saja. Saat ini mungkin yang bikin reservasi adalah yang sedang login, tapi bisa saja ada kebutuhan orang lain membantu membuat reservasi. Contoh, Admin FO membuatkan booking/reservasi karena user pegawai ga bisa bikin sendiri (misal sedang berhalangan). Maka harusnya email dikirimkan ke pegawai tersebut, bukan ke Admin FO 😁 

Sekarang walau fungsionalnya belum ada, tapi sebaiknya kode kita mulai dirancang agar ke depan effort perubahannya tidak terlalu banyak.

Maka ini lebih relevan jika mengirim email dengan tujuan adalah alamat email yang dipakai untuk reservasi. Jadi tidak diarahkan ke user yang sedang login.

2021-02-24 04:34 UTC, rizkyrmsyah commented on app/Listeners/SendReservationEmail.php
> +        Mail::to(auth()->user()->email)->send(new ReservationApprovalMail($reservation));
oh iya betul betul setuju mas 😄

2021-02-24 04:50 UTC, yohang88 commented on app/Http/Controllers/V1/ReservationController.php
> +            event(new ReservationEmail($reservation));
Nah berarti ada 2 events:
```php
protected $listen = [
    ReservationCreated::class => [
        SendReservationEmail::class,
        CreateZoomSchedule::class,
    ],
    ReservationUpdated::class => [
        SendReservationEmail::class,
        CreateZoomSchedule::class,
    ]
];
```

Namun pada intinya secara holistik, "Event" adalah sebuah peristiwa, kejadian. "Saat order dibayar", "Saat order dikirim", "Saat order dibatalkan." Sedangkan "Kirim email", "Booking di Zoom", itu adalah "Aksi".

Dalam kasus kita, tentu yang disebut kejadian/peristiwa, adalah "Saat reservasi berhasil dibuat", "saat reservasi berhasil diupdate", dsb. 😁 

Maka kita tempatkan mana yang Event, mana yang Listener agar lebih sesuai konteksnya 😁

2021-02-24 04:58 UTC, setiadijoe commented on database/migrations/2021_02_21_224312_add_join_url_to_reservations_table.php
> +            //
done ya mang

2021-02-24 05:06 UTC, setiadijoe commented on app/Http/Controllers/V1/ReservationController.php
> +            event(new ReservationEmail($reservation));
https://laravel.com/docs/8.x/events#introduction
secara dokumentasi di sini untuk deklarasinya ada cara ini sih mas,

`
public function shouldDiscoverEvents()
{
    return true;
}
`

2021-02-24 05:07 UTC, setiadijoe commented on app/Http/Controllers/V1/ReservationController.php
> +            event(new ReservationEmail($reservation));
jadi gak dijabarin seperti yang mas buat itu

2021-02-24 06:34 UTC, rindibudiaramdhan commented
> > sip tinggal ditest lanjut lagi yak
> 
> sebetulnya ada caranya gak sih untuk ngemock satu fungsi di laravel? kan ini errornya di bagian createMeeting(), yang mana itu teh akses ke Zoom API, kira-kira referensinya ada gak yang kang @rindibudiaramdhan ?

kalau ini saya belum pernah menerapkannya. tapi setahu saya di Zoom API ada test API.
Mungkin apakah yang seperti ini yang dicari kang @setiadijoe ? https://marketplace.zoom.us/docs/api-reference/testing-zoom-apis

2021-02-24 07:18 UTC, setiadijoe commented
> > > sip tinggal ditest lanjut lagi yak
> > 
> > 
> > sebetulnya ada caranya gak sih untuk ngemock satu fungsi di laravel? kan ini errornya di bagian createMeeting(), yang mana itu teh akses ke Zoom API, kira-kira referensinya ada gak yang kang @rindibudiaramdhan ?
> 
> kalau ini saya belum pernah menerapkannya. tapi setahu saya di Zoom API ada test API.
> Mungkin apakah yang seperti ini yang dicari kang @setiadijoe ? https://marketplace.zoom.us/docs/api-reference/testing-zoom-apis

Udah kang, udah ketemu caranya, jadinya zoomnya dimasukkin ke dalam Event, terus untuk testnya jadinya kalau ada event itu diignore eventnya gak dieksekusi, sekarang kan jadi lolos testnya

2021-02-24 08:04 UTC, yohang88 approved these changes

2021-02-24 08:06 UTC, merged