add endpoint list all reservation for FE calendar
jabardigitalservice/reservasi-backend pull request #59
Opened 2021-02-25 10:50 UTC by rachadiannovansyah

This PR refer to task --> https://trello.com/c/z7yp03Dx

Overview:
- Add endpoint baru untuk mendapatkan semua data reservasi (untuk calendar di FE)
- Sudah ditambahkan unit test

Note:
- Tested

cc: kang @rindibudiaramdhan @ayocodingit @setiadijoe @rizkyrmsyah

2021-02-25 12:34 UTC, ayocodingit requested changes

2021-02-25 12:34 UTC, ayocodingit commented on app/Http/Controllers/V1/ReservationListAllController.php
> +        return ReservationResource::collection(Reservation::all());
Boleh di tambahkan fitur filter tanggal gak kang @rachadiannovansyah menghindari load ribuan data
Sediakan range tanggal minimal satu bulan karena di UI kalender nya juga range nya perbulan

2021-02-25 23:38 UTC, ayocodingit approved these changes

2021-02-25 23:41 UTC, ayocodingit commented
Nice sudah ada filter perbulan nuhun kang @rachadiannovansyah

2021-02-25 23:48 UTC, rachadiannovansyah commented
> Nice sudah ada filter perbulan nuhun kang @rachadiannovansyah

sami2 kang :pray: @ayocodingit

2021-02-26 01:11 UTC, setiadijoe approved these changes

2021-02-26 01:13 UTC, merged