Feature reservation cc
jabardigitalservice/reservasi-backend pull request #74
Opened 2021-03-15 08:46 UTC by samudra-ajri

Add command center reservation functionalities.

2021-03-15 10:19 UTC, khihadysucahyo commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +            DB::beginTransaction();
penasaran, penggunaan [Database Transactions](https://laravel.com/docs/8.x/database#database-transactions) di fungsi `store` disini tujuannya apa ya? soalnya kalo ngeliat cuman ada satu operasi yaitu `create` gitu di dalamnya.

2021-03-15 14:50 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +            DB::beginTransaction();
Tujuannnya buat transaksi di sql kang, tapi sepertinya berlebihan mengingat hanya ada satu operasi.

2021-03-16 00:29 UTC, rachadiannovansyah commented on app/Http/Controllers/V1/ShiftController.php
> +    }
kang @iprasetyaa kalo boleh saran controller ini kalo hanya dipake untuk satu fungsi bagusnya dibuat Single Action Controller aja kang, kan fungsi create, store dsb nya gak akan kepakai yaa? *cmiiw :smiley: 
https://laravel.com/docs/8.x/controllers#single-action-controllers

2021-03-16 00:35 UTC, iprasetyaa commented on app/Http/Controllers/V1/ShiftController.php
> +    }
Coba saya pelajari dulu kang @rachadiannovansyah, cuman niat awalnya karena di backlog ada crud / manage shift, jadi sekalian dibuatkan 😅

2021-03-16 00:57 UTC, rachadiannovansyah approved these changes

2021-03-16 01:53 UTC, yohang88 commented on app/Http/Controllers/V1/ShiftController.php
> +    }
Ada method `create()`, `edit()`, tentu ini ga dibutuhkan karena yang dibuat adalah API resource 😁

2021-03-16 02:17 UTC, yohang88 requested changes
Cek-cek yes @iprasetyaa @samudra-ajri 😁

2021-03-16 02:17 UTC, yohang88 commented on app/Http/Resources/PublicCCReservationResource.php
> +class PublicCCReservationResource extends JsonResource
Sebaiknya ini disatukan di CCReservationResource karena class/modelnya sama 😁

2021-03-16 02:17 UTC, yohang88 commented on app/Mail/CCReservationNotificationMail.php
> +                $this->subject = '[Command Center Reservation] Permohonan Reservasi Dikabulkan';
Gunakan language/dictionary file yang sudah tersedia di Laravel 😁 

Dikabulkan = disetujui.

2021-03-16 02:17 UTC, yohang88 commented on app/Mail/CCReservationNotificationMail.php
> +                        'from' => env('MAIL_FROM_NAME'),
Tidak boleh memanggil `env()` langsung, gunakan `config()` instead.

Dan fyi di config, `MAIL_FROM_NAME` ini bisa dibuat global 😁

2021-03-16 02:17 UTC, yohang88 commented on app/Models/CommandCenterReservation.php
> +        'reservation_date' => 'datetime',
Ini ada redundant di `$dates` dan `$casts`, pilih salah satu saja 😁

2021-03-16 02:17 UTC, yohang88 commented on app/Models/CommandCenterReservation.php
> +        'approval_status' => CommandCenterReservationStatusEnum::class . ':nullable'
Kenapa dibuat `nullable` ya? 😁

2021-03-16 02:17 UTC, yohang88 commented on database/migrations/2021_03_09_034512_create_command_center_reservations_table.php
> +            $table->enum('shift', ['1', '2']);
Shift ini apa ya maksudnya kok 1 dan 2? 

Padahal bisa saja ini dinamis, misal dalam 1 hari bisa 3-4 shift 😁

2021-03-16 02:17 UTC, yohang88 commented on resources/views/emails/ccReservationNotification.blade.php
> +        <div>{{ $organization_name }}</div>
Jika dia bukan dari organisasi/instansi, tampilannya akan seperti apa? 😁

2021-03-16 02:17 UTC, yohang88 commented on resources/views/emails/ccReservationNotification.blade.php
> +        <div>Email: digital.service@jabarprov.go.id</div>
Alamat email jangan dihardcode.

2021-03-16 02:17 UTC, yohang88 commented on resources/views/emails/ccReservationNotification.blade.php
> +<head>
Ini belum optimal menggunakan templating `blade`, sebaiknya gunakan `header`, `footer`, yang reusable di banyak template 😁

2021-03-16 02:17 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +    public function checkAvailability(Request $request)
Ini diluar fungsional CRUD Reservasi Command Center.

Maka sesuai prinsip Single Responbility, untuk cek availability ini bisa dipecah ke controller terpisah, misal Single Action Controller.

2021-03-16 02:17 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +        $shift = Shift::find($request->input('shift_id'));
Apa yang terjadi jika shift tidak ditemukan atau `null` ?

2021-03-16 02:17 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +        }
Coba direfactor agar tidak perlu `else` 😁

2021-03-16 02:17 UTC, yohang88 commented on app/Models/CommandCenterReservation.php
> +    }
Ini udah dipakai semua? 😁

2021-03-16 02:17 UTC, yohang88 commented on app/Models/Shift.php
> +class Shift extends Model
Naming class modelnya terlalu general, sebaiknya mendekati maksudnya adalah shift untuk reservasi 😁

2021-03-16 02:17 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +class CommandCenterReservationController extends Controller
Ini CRUD untuk Admin, atau yang digunakan Public untuk Register ya? Fungsional CRUD dan untuk Registrasi Publik pasti berbeda tujuan dan caranya, kenapa disatukan ya? 😁

2021-03-16 02:17 UTC, yohang88 commented on app/Http/Controllers/V1/ShiftController.php
> +class ShiftController extends Controller
Namanya terlalu general 😁

2021-03-16 02:17 UTC, yohang88 commented on app/Enums/CommandCenterReservationStatusEnum.php
> + * @method static self rejected()
Enum ini mendekati constant, bisa mengikuti standard PHP-PSR1 https://www.php-fig.org/psr/psr-1/

2021-03-16 02:17 UTC, yohang88 commented on app/Enums/ShiftStatusEnum.php
> + * @method static self not_active()
Enum ini mendekati constant, bisa mengikuti standard PHP-PSR1 https://www.php-fig.org/psr/psr-1/

2021-03-16 02:17 UTC, yohang88 commented on app/Http/Requests/CommandCenterReservationRequest.php
> +    public function rules()
Belum ada validasi checking apakah kuota penuh atau tidak.

2021-03-16 02:18 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +class CommandCenterReservationController extends Controller
Termasuk belum ada checking otorisasi hak aksesnya juga.

2021-03-16 02:24 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +            DB::beginTransaction();
Sesuatu yang tidak memberikan nilai tambah, dampak, manfaat, tidak usah dilakukan gans 😁

2021-03-16 02:28 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +        }
biar ketauan sih mas kalau kirim emailnya gagal 😁

2021-03-16 02:29 UTC, firmanJS commented on resources/views/emails/ccReservationNotification.blade.php
> +        <div>Email: digital.service@jabarprov.go.id</div>
ikut numbrung best practice di laravel pemanggilan env di blade seperti inikah mas baiknya langsung direct `{{ env('EMAIL')}}`

2021-03-16 02:31 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +                'user_id_reservation' => $request->user()->uuid,
Ini sudah di fix mas di commit https://github.com/jabardigitalservice/reservasi-backend/commit/a858258343602233281ef45a0dac3913fbd3a020

2021-03-16 02:33 UTC, iprasetyaa commented on database/migrations/2021_03_09_034512_create_command_center_reservations_table.php
> +            $table->enum('shift', ['1', '2']);
Ini sudah diperbaiki di commit terbaru di file https://github.com/jabardigitalservice/reservasi-backend/blob/0273cb96e70a4a34360a3003a4791ca86e0403a2/database/migrations/2021_03_12_044156_alter_command_center_reservation_table_add_shift_id.php

2021-03-16 02:35 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +    public function checkAvailability(Request $request)
Ini sudah dibuat single action controller di commit https://github.com/jabardigitalservice/reservasi-backend/commit/de8c16abd6b085f0c29b1e7639705214acd56d71

2021-03-16 02:37 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +class CommandCenterReservationController extends Controller
Mas Yoga, kalau dibuat kayak gini apakah diperbolehkan? jadi sama saya untuk store & show dibuat public, kalau kebutuhannya kayaknya masih sama mas. https://github.com/jabardigitalservice/reservasi-backend/commit/ae7b99a2dc1983e1ffa5237e838cee3ea51969a6

2021-03-16 02:39 UTC, iprasetyaa commented on app/Http/Requests/CommandCenterReservationRequest.php
> +    public function rules()
untuk pengecekan saya buatkan ke endpoint ini https://github.com/jabardigitalservice/reservasi-backend/commit/de8c16abd6b085f0c29b1e7639705214acd56d71

<img width="1061" alt="Screen Shot 2021-03-16 at 09 38 36" src="https://user-images.githubusercontent.com/21275214/111247894-6a53c780-863b-11eb-88c2-0f75822a4b67.png">

Lebih baik ditambahkan validasi lagi juga ya mas ketika akan simpan reservasi?

2021-03-16 02:53 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +            DB::beginTransaction();
Siap Mas Yoga 🙏

2021-03-16 02:59 UTC, iprasetyaa commented on app/Models/CommandCenterReservation.php
> +    }
Belum mas, lebih baik saya hapus aja dulu 🙏

2021-03-16 03:10 UTC, yohang88 requested changes

2021-03-16 03:10 UTC, yohang88 commented on resources/views/emails/ccReservationNotification.blade.php
> +        <div>Email: digital.service@jabarprov.go.id</div>
@firmanJS best practicenya pakai `config()` man, tidak langsung ke env 😁 https://laravel.com/docs/8.x/configuration

Jika pakai `env()`, nanti tidak bisa di-cache dan setiap saat harus load 😁

2021-03-16 03:11 UTC, yohang88 commented on app/Http/Requests/CommandCenterReservationRequest.php
> +    public function rules()
Ya kalau ada hacker pasti akan nembak langsung ke proses menyimpan, bisa skip `checkin availability` ini.

2021-03-16 03:12 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +class CommandCenterReservationController extends Controller
Sebaiknya dipisahkan antara proses logic reservasi dari masyarakat, dan proses logic CRUD admin, agar separation of concernnya juga jelas 😁

2021-03-16 03:12 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +class CommandCenterCloseDateController extends Controller
Punten, Mas..
Harusnya di branch baru

2021-03-16 03:15 UTC, iprasetyaa commented on app/Http/Requests/CommandCenterReservationRequest.php
> +            'email' => 'required',
Untuk validasi, saya sudah coba perbaiki, apakah sudah tepat Mas? https://github.com/jabardigitalservice/reservasi-backend/pull/74/commits/7ad97a32b95e55f34586ee30aadea1936b5820b3

2021-03-16 03:15 UTC, iprasetyaa commented on app/Http/Requests/CommandCenterReservationRequest.php
> +            'phone_number' => 'string|required|max:14',
Untuk validasi, saya sudah coba perbaiki, apakah sudah tepat Mas? https://github.com/jabardigitalservice/reservasi-backend/pull/74/commits/7ad97a32b95e55f34586ee30aadea1936b5820b3

2021-03-16 03:15 UTC, iprasetyaa commented on app/Http/Requests/CommandCenterReservationRequest.php
> +            'nik' => 'string|required|max:16',
Untuk validasi, saya sudah coba perbaiki, apakah sudah tepat Mas? https://github.com/jabardigitalservice/reservasi-backend/pull/74/commits/7ad97a32b95e55f34586ee30aadea1936b5820b3

2021-03-16 03:35 UTC, iprasetyaa commented on app/Http/Requests/CommandCenterReservationRequest.php
> +    public function rules()
Oke baik Mas, coba saya tambahkan double validasinya

2021-03-16 03:36 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +class CommandCenterReservationController extends Controller
Siap Mas Yoga 😁

2021-03-16 03:43 UTC, samudra-ajri commented on app/Mail/CCReservationNotificationMail.php
> +                        'from' => env('MAIL_FROM_NAME'),
fixed, Mas.. :+1:

2021-03-16 03:44 UTC, samudra-ajri commented on resources/views/emails/ccReservationNotification.blade.php
> +        <div>{{ $organization_name }}</div>
fixed, Mas..
Sudah ditambahkan conditional. :+1:

2021-03-16 03:45 UTC, samudra-ajri commented on resources/views/emails/ccReservationNotification.blade.php
> +        <div>Email: digital.service@jabarprov.go.id</div>
fixed, Mas.. Sudah menggunakan config() dalam pemanggilan. :+1:

2021-03-16 03:46 UTC, firmanJS commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +class CommandCenterCloseDateController extends Controller
di git reset aja jika nyampur code nya, nanti push lagi ke branch baru

2021-03-16 05:04 UTC, samudra-ajri commented on app/Mail/CCReservationNotificationMail.php
> +                $this->subject = '[Command Center Reservation] Permohonan Reservasi Dikabulkan';
Punten, Mas..
Sudah saya tambahkan message untuk reservasi ketika accepted atau rejected di language/dictionary, boleh koreksinya, Mas.

Hatur nuhun

2021-03-16 06:03 UTC, iprasetyaa commented on app/Http/Controllers/V1/ShiftController.php
> +class ShiftController extends Controller
Mas, untuk penaamaan sudah saya rubah dari Shift jadi CommandCenterShift. https://github.com/jabardigitalservice/reservasi-backend/pull/74/commits/a1a8525c8d88984ae20cfba8b5e7199a5acdd8ea

2021-03-16 06:04 UTC, iprasetyaa commented on app/Enums/ShiftStatusEnum.php
> + * @method static self not_active()
Ini sudah saya rubah menjadi ACTIVE & NOT_ACTIVE

2021-03-16 06:22 UTC, iprasetyaa commented on app/Models/CommandCenterReservation.php
> +        'reservation_date' => 'datetime',
Oke mas ini sudah di fix di sini 🙏 https://github.com/jabardigitalservice/reservasi-backend/pull/74/commits/3a7cd2e649b283cc45a786b5f2ac24eb8d9daf9a

2021-03-16 06:31 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterAvailabilityController.php
> +                ]
Bisa mas, ini udah saya perbaiki dicommit ini 🙏 https://github.com/jabardigitalservice/reservasi-backend/pull/74/commits/521c7d2281507d4a52ea52579021cdb3e62d53e5

2021-03-16 06:32 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterAvailabilityController.php
> +        $shift = Shift::find($request->input('shift_id'));
Saya sudah melakukan perubahan mas di commit ini https://github.com/jabardigitalservice/reservasi-backend/pull/74/commits/521c7d2281507d4a52ea52579021cdb3e62d53e5

Kalau sekarang ketika null itu HTTP Status Code nya 404, apakah sudah tepat Mas?

2021-03-16 10:02 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +        $shift = Shift::find($request->input('shift_id'));
Ini sudah diganti menggunakan findOrFail jadi ketika tidak ada, return http response status 404. saya update di commit de8c16a

2021-03-16 10:03 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +        }
ini sudah tidak menggunakan else mas. saya update di commit de8c16a

2021-03-16 10:04 UTC, iprasetyaa commented on app/Models/Shift.php
> +class Shift extends Model
Mas, untuk penaamaan sudah saya rubah dari Shift jadi CommandCenterShift. a1a8525

2021-03-16 10:05 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +        $shift = Shift::find($request->input('shift_id'));
sudah di move ke single action controller mas

2021-03-16 14:41 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +class CommandCenterCloseDateController extends Controller
Hatur nuhun Mas Yoga dan Kang Firman. Untuk fitur ini sudah dihapus untuk disimpan di branch baru.

2021-03-16 15:22 UTC, samudra-ajri commented on app/Http/Requests/CommandCenterReservationRequest.php
> +class CommandCenterReservationRequest extends FormRequest
Terima kasih, Mas.. Class name sudah disesuaikan.
9f14935

2021-03-16 15:23 UTC, samudra-ajri commented on app/Http/Resources/PublicCCReservationResource.php
> +class PublicCCReservationResource extends JsonResource
Sip, Mas.. Resource tersebut sudah di-overwrite dengan CCReservationResource.
9f14935

2021-03-16 15:28 UTC, samudra-ajri commented on app/Models/CommandCenterReservation.php
> +        'approval_status' => CommandCenterReservationStatusEnum::class . ':nullable'
Seharusnya penempatan sifat nullable pada approval status tidak diperlukan, Mas. Maka nullable di sini sudah diperbaiki dengan menghilangkannya.
9f14935

2021-03-16 15:30 UTC, samudra-ajri commented on app/Models/CommandCenterReservation.php
> +    }
Karena fungsi-fungsi tersebut belum digunakan semua, maka model ini sudah diperbaiki dengan menghilangkan fungsi-fungsi yg belum digunakan tersebut.

Hatur nuhun, Mas.
9f14935

2021-03-17 00:40 UTC, samudra-ajri commented on resources/views/emails/ccReservationNotification.blade.php
> +<head>
Siap, Mas..
Sudah disesuaikan. Hatur nuhun

2021-03-17 08:47 UTC, iprasetyaa commented on app/Http/Requests/CommandCenterReservationRequest.php
> +    public function rules()
Mas Yoga, ini sudah saya tambahkan di commit ini https://github.com/jabardigitalservice/reservasi-backend/pull/74/commits/ef6f35c89c43610099dde41d425e6fd894fab122

2021-03-17 09:05 UTC, iprasetyaa commented on app/Enums/CommandCenterReservationStatusEnum.php
> + * @method static self rejected()
Mas Yoga, penamaan enum sudah saya fix di commit 17fd425

2021-03-17 09:53 UTC, yohang88 reviewed
Cek cek lagi 😁

2021-03-17 09:53 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +    }
Di endpoint untuk public, kenapa ada feature untuk list reservasi?

2021-03-17 09:53 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +        Mail::to($reservation->email)->send(new CCReservationNotificationMail($reservation));
Sebaiknya kurangi menumpuk semua logic di controller. Saat ini kan:
1. Menyimpan ke DB
2. Mengirim email

Mengirim email ini bisa dipisahkan menggunakan Event & Listener yang dimiliki Laravel.

2021-03-17 09:53 UTC, yohang88 commented on app/Http/Requests/CommandCenterReservationCreateRequest.php
> +        $maxShift = ($shift) ? $shift->capacity : 20;
Value `20` ini sebaiknya dibuat `config`, sehingga kedepan mudah dicari jika akan ada perubahan.

2021-03-17 09:53 UTC, yohang88 commented on app/Http/Requests/CommandCenterReservationCreateRequest.php
> +            'email' => 'required|email:rfc,dns',
`rfc,dns` itu apa ya? Bukannya pakai `email` sudah cukup?

2021-03-17 10:03 UTC, iprasetyaa commented on app/Http/Requests/CommandCenterReservationCreateRequest.php
> +            'email' => 'required|email:rfc,dns',
Saya nambahin validasi style lain
https://laravel.com/docs/8.x/validation#rule-email

Bila dirasa berlebihan, bisa saya ubah ke email aja mas 😁

2021-03-17 10:04 UTC, iprasetyaa commented on app/Http/Requests/CommandCenterReservationCreateRequest.php
> +        $maxShift = ($shift) ? $shift->capacity : 20;
Bagusnya dibuat file config yang di set dari .env atau dibuat const aja mas?

2021-03-17 10:04 UTC, iprasetyaa commented on app/Http/Requests/CommandCenterReservationCreateRequest.php
> +        $maxShift = ($shift) ? $shift->capacity : 20;
Bagusnya dibuat file config yang di set dari .env atau dibuat const aja mas?

2021-03-17 10:04 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +        Mail::to($reservation->email)->send(new CCReservationNotificationMail($reservation));
Baik Mas Yoga, bisa saya tambahkan event agar tidak numpuk di controller 😁🙏

2021-03-17 10:05 UTC, iprasetyaa commented on app/Enums/ShiftStatusEnum.php
> + * @method static self not_active()
Ini saya ubah penamaan file nya disini ya terkait issue nama shift yg terlalu general https://github.com/jabardigitalservice/reservasi-backend/pull/74/commits/befa640caac645205bcd0462be8e1c5d518ce4cd

2021-03-17 10:07 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +                'user_id_reservation' => $request->user()->uuid,
Eh ini jadinya gimana? Kalau udah dicommit harusnya berubah di sini juga.

2021-03-17 10:09 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +        try {
Selalu pertanyaan yang sama, kenapa perlu dibungkus try-catch? Ada hal yang tidak dihandle framework saat gagal/error?

2021-03-17 10:11 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +    }
Rencananya mau bikin endpoint untuk get a reservation by code_reservation, Mas..
Karena menggunakan api resource, maka saya pakai yg fungsi index untuk melakukan  query.

Adapun kembalian data dari fungsi tersebut hanya menampilkan array yg berisi satu detail reservasi berdasarkan code_reservasi.

Maaf, Mas..
Mungkin boleh tau cara yang seharusnya seperti apa?

Hatur nuhun, Mas

2021-03-17 10:16 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +        Mail::to($reservation->email)->send(new CCReservationNotificationMail($reservation));
Siap, saya coba pelajari, Mas..
Hatur nuhun  masukannya, Mas

2021-03-17 12:18 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +        Mail::to($reservation->email)->send(new CCReservationNotificationMail($reservation));
Terima kasih Mas Yoga, sending notificaiton email sudah dibuat menggunakan event & listener.

Mohon koreksinya, Mas..
Apabila penerapannya kurang pas.

Hatur nuhun
c8174c5

2021-03-17 17:29 UTC, yohang88 commented on app/Http/Requests/CommandCenterReservationCreateRequest.php
> +        $maxShift = ($shift) ? $shift->capacity : 20;
Sebaiknya sesuai namanya, untuk hal-hal yang configurable (bisa diubah-ubah) maka di config lebih pas.

2021-03-18 01:40 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +    }
Setuju, Mas Yoga..
Tapi di sini rencananya ingin menampilkan 1 record berdasarkan reservation_code, Mas..
Klw ga salah, method show() hanya dapat mencari berdasarkan id ya, Mas?

Mohon koreksinya, Mas.
Hatur nuhun

2021-03-18 02:02 UTC, iprasetyaa commented on app/Http/Requests/CommandCenterReservationCreateRequest.php
> +        $maxShift = ($shift) ? $shift->capacity : 20;
Oke mas sudah saya buatkan dengan file config 🙏  3217564

2021-03-18 02:03 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterReservationController.php
> +        try {
setelah saya coba kemarin ini bisa mas tanpa try catch, dan sudah saya perbaiki, terima kasih masukannya mas 🙏 https://github.com/jabardigitalservice/reservasi-backend/pull/74/commits/779e9c7cecdbed651a5cc849d090bcd12d2eb0f1

2021-03-18 02:14 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +    }
Apakah sebaiknya dipisah dari  route api resource ya, Mas?
Untuk membuat method baru, getByReservationCode misalnya?

2021-03-18 03:32 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +    }
Baik, Mas Yoga..
Sudah dimodifikasi setelah berguru dari Kang @khihadysucahyo

Mohon koreksinya, Mas..
Hatur nuhun
b333805

2021-03-18 09:39 UTC, khihadysucahyo approved these changes

2021-03-19 08:22 UTC, yohang88 approved these changes

2021-03-19 08:23 UTC, merged