add command center disable dates functionality
jabardigitalservice/reservasi-backend pull request #77
Opened 2021-03-22 07:59 UTC by samudra-ajri

- Sebagai Admin FO, saya dapat men-disable waktu-waktu tertentu yang tidak bisa direservasi kunjungan (misal hari Libur Nasional, kunjungan Gubernur, Pemerintah Pusat, dsb).
- To do:
-- create disabled dates table
-- admin can CRUD
-- public can see the disabled days

2021-03-22 08:25 UTC, firmanJS approved these changes

2021-03-22 08:40 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +        $close_day->update($request->validated());
@samudra-ajri kayaknya kalau pake validated notes nya gabisa di update jri

2021-03-22 08:47 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +        $close_day->update($request->validated());
Siap, Kang..
Sudah diubah pakai method only.

Hatur nuhun, Kang

2021-03-22 08:48 UTC, iprasetyaa approved these changes

2021-03-22 08:59 UTC, yohang88 requested changes
Minor aja @samudra-ajri 😁

2021-03-22 08:59 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +    public function show(CommandCenterCloseDate $close_day)
Btw ini campur-campur ya standar naming variable 😁 Sebaiknya ngikutin standar Laravel pakai `camelCase`, jadi `$closeDay` lebih sesuai (ini berlaku semua variable di sini yess)

2021-03-22 08:59 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +    public function __construct()
Coba mulai gunakan `Policy` untuk authorizationnya 😁 

https://laravel.com/docs/8.x/authorization

2021-03-22 09:00 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +    public function show(CommandCenterCloseDate $close_day)
Siap, Mas..
Hatur nuhun

2021-03-22 09:01 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +    public function __construct()
Mantap, Mas..
Hatur nuhun

2021-03-22 15:13 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +    public function show(CommandCenterCloseDate $close_day)
Siap, Mas..
Naming sudah desesuaikan.

Hatur nuhun
3dbad41

2021-03-22 15:15 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +    public function __construct()
Policy sudah coba ditambahkan, Mas..

Mohon koreksinya
Hatur nuhun
32d2f73

2021-03-23 01:57 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +    public function show(CommandCenterCloseDate $close_day)
oke sip mantap @samudra-ajri

2021-03-23 01:58 UTC, yohang88 approved these changes
oke sip mantap @samudra-ajri

2021-03-23 01:58 UTC, merged