add sorting command center disabled dates list functionality
jabardigitalservice/reservasi-backend pull request #83
Opened 2021-03-24 07:40 UTC by samudra-ajri

Add sorting functionality for command center disabled dates list.

@jabardigitalservice/jds-backend

2021-03-24 07:46 UTC, iprasetyaa approved these changes

2021-03-24 10:44 UTC, aldidoanta requested changes

2021-03-24 10:44 UTC, aldidoanta commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +        return $records->orderBy($sortBy, $orderBy);
Kang @samudra-ajri sekedar usulan, untuk variabel `$orderBy`, gimana kalau diganti namanya jadi `$direction` atau `$orderDirection`? Soalnya menurut saya, makna `$sortBy` dan `$orderBy` itu mirip mirip.

[Referensi function signature `orderBy`](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Query/Builder.php#L1961)

2021-03-24 13:11 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +        return $records->orderBy($sortBy, $orderBy);
Siap, hatur nuhun, Kang Aldo..
Setuju sama penamaannya, Kang. :+1: 

2b9890a

2021-03-24 23:47 UTC, ayocodingit commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +        return $records->orderBy($sortBy, $orderBy);
Nanti didiskusikan juga ke frontend perubahan parameter dari orderBy ke orderDirection

2021-03-25 00:33 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterCloseDateController.php
> +        return $records->orderBy($sortBy, $orderBy);
Siap, Kang @ayocodingit.. :+1: 
Hatur nuhun

2021-03-25 00:34 UTC, ayocodingit approved these changes

2021-03-25 06:34 UTC, aldidoanta approved these changes

2021-03-25 06:34 UTC, merged