Add CRUD shift command center
jabardigitalservice/reservasi-backend pull request #90
Opened 2021-03-29 07:35 UTC by iprasetyaa

Membuat CRUD untuk mengatur jadwal shift dan capacity 

CC : @jabardigitalservice/jds-backend @samudra-ajri @yohang88

2021-03-29 07:51 UTC, samudra-ajri commented on app/Http/Requests/CommandCenterShiftUpdateRequest.php
> +        ];
Punten, Kang..
Klw misalkan ngga dibuat required, gimana, Kang? Klw misalkan ada atribut yg ngga diupdate nanti auto pakai value sebelumnya.

Jd, ketika hanya ingin update salah satu atribut, cukup mengisi atribut yg diinginkan saja.

cmiiw.. hhe

2021-03-29 07:52 UTC, iprasetyaa commented on app/Http/Requests/CommandCenterShiftUpdateRequest.php
> +        ];
woke jri mantap tak fix dulu

2021-03-29 07:55 UTC, iprasetyaa commented on app/Http/Requests/CommandCenterShiftUpdateRequest.php
> +        ];
eh bentar, kalau dari FE kalau gitu ga ngirim semua body request nya ya? aku mikirnya kenapa required karena nanti dikirim semua valuenya di body request

2021-03-29 07:58 UTC, samudra-ajri commented on app/Http/Requests/CommandCenterShiftUpdateRequest.php
> +        ];
Hum.. Bisa jadi, Kang..
Tapi kadang suka ada gening, form yg updatenya cuma per-atribut, tea.. haha..

2021-03-29 08:05 UTC, iprasetyaa commented on app/Http/Requests/CommandCenterShiftUpdateRequest.php
> +        ];
Bisa juga jri, tapi sama aja kan ya kalau dari FE nya ngirim semua field nya dipasang required bisa juga?

2021-03-29 13:25 UTC, samudra-ajri approved these changes

2021-03-30 01:32 UTC, rachadiannovansyah commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +        $record->save();
sedikit saran kang, proses store ini kayanya bisa di sulap jadi lebih ringkas :grin: 
`$record = CommandCenterShift::create($request->validated);`
cmiiw :grin:

2021-03-30 01:34 UTC, ayocodingit requested changes

2021-03-30 01:34 UTC, ayocodingit commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    }
Ini return nya mana yah kang @iprasetyaa

2021-03-30 01:34 UTC, ayocodingit commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    public function update(CommandCenterShiftUpdateRequest $request, CommandCenterShift $commandCenterShift)
Form request update dan create sebenernya bisa aja di cukup menggunakan satu form request aja untuk bagian validasi unique bisa menggunakan rule unique ignore kang @iprasetyaa

2021-03-30 01:41 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    }
ini saya mikirnya FE hanya lihat dari HTTP Status Code aja, jadi saya pake bawaan framework ketika success delete kang @ayocodingit

2021-03-30 01:42 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    public function update(CommandCenterShiftUpdateRequest $request, CommandCenterShift $commandCenterShift)
Oke kang terima kasih masukannya @ayocodingit 😁

2021-03-30 01:43 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +        $record->save();
nuhun kang @rachadiannovansyah sarannya, coba saya persingkat dulu 😁

2021-03-30 01:49 UTC, ayocodingit commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    }
iya betul tapi biar lebih informatif di tambahkan response message deleted atau apa walau message gak kepake tetapi informasi nya jelas oh berhasil berhasil dari pada blank putih #cwiiw

2021-03-30 01:51 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    public function update(CommandCenterShiftUpdateRequest $request, CommandCenterShift $commandCenterShift)
Kang kalau saya liat di existing project itu untuk create & update dibuat form request terpisah, gimana ya kang baiknya? @ayocodingit

2021-03-30 01:54 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +        $record->save();
Kang sudah saya persingkat ya code nya @rachadiannovansyah 

https://github.com/jabardigitalservice/reservasi-backend/pull/90/commits/08b96d549dacc27e205b5d0490cfb7f9f3735301

2021-03-30 01:57 UTC, azophy approved these changes

2021-03-30 01:58 UTC, rachadiannovansyah approved these changes

2021-03-30 02:03 UTC, ayocodingit commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    public function update(CommandCenterShiftUpdateRequest $request, CommandCenterShift $commandCenterShift)
baiknya improve saja yang baru kang jangan liat yang existing karena kan kita sama sama tahap belajar :)

2021-03-30 02:11 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    public function update(CommandCenterShiftUpdateRequest $request, CommandCenterShift $commandCenterShift)
Oke kang coba saya improve dulu🙏

2021-03-30 02:11 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    }
i see, oke kang saya tambahkan ✌️

2021-03-30 02:23 UTC, ayocodingit commented on routes/api.php
> +            ->only(['show', 'store', 'update', 'destroy']);
ini alasan menggunakan only kenapa yah kang @iprasetyaa

2021-03-30 02:39 UTC, rindibudiaramdhan commented on routes/api.php
> +            ->only(['show', 'store', 'update', 'destroy']);
kayaknya `only` nya bisa dilepas dulu. kecuali ada concern tertentu terkait API yang hanya bisa digunakan?

2021-03-30 02:42 UTC, rindibudiaramdhan requested changes

2021-03-30 02:42 UTC, rindibudiaramdhan commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    }
mungkin bisa diuji coba dahulu untuk kondisi-kondisi tidak successnya kang @iprasetyaa .
kira-kira returnnya bisa dihandle oleh FE tidak untuk kondisi-kondisi lainnya.

2021-03-30 03:04 UTC, iprasetyaa commented on routes/api.php
> +            ->only(['show', 'store', 'update', 'destroy']);
Ini teh si endpoint index nya bisa di akses di public kang, apa sebaiknya saya buat file baru untuk list shift nya di single action controller saja @rindibudiaramdhan @ayocodingit ?

2021-03-30 03:06 UTC, ayocodingit commented on routes/api.php
> +            ->only(['show', 'store', 'update', 'destroy']);
berarti bisa menggunakan except kang untuk pengecualian yah

2021-03-30 03:10 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    }
Saya coba dulu kang @rindibudiaramdhan

2021-03-30 03:26 UTC, iprasetyaa commented on routes/api.php
> +            ->only(['show', 'store', 'update', 'destroy']);
oh i see, lebih ringkas, oke kang 🙏

2021-03-30 03:34 UTC, iprasetyaa commented on routes/api.php
> +            ->only(['show', 'store', 'update', 'destroy']);
Done kang @ayocodingit @rindibudiaramdhan  sudah diperbaiki https://github.com/jabardigitalservice/reservasi-backend/pull/90/commits/a84cb8c9d03b7cece9758cb4d3b898a9c21ecc3a

2021-03-30 03:43 UTC, iprasetyaa commented
> kalau satu mah jangan menggunakan array kang @iprasetyaa cukup `except('index')`

okey kang siaaap 😁🙏

2021-03-30 04:06 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    }
kang ini udah coba saya fix sesuai obrolan tadi @rindibudiaramdhan https://github.com/jabardigitalservice/reservasi-backend/pull/90/commits/24d4e7bdc6b27270857fe3675a1c33b5dc70fee9

2021-03-30 04:11 UTC, ayocodingit commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +        return response()->json(['message' => 'deleted'], Response::HTTP_OK);
kalau response nya 200 mah cukup message nya aja kang @iprasetyaa gak usah `Response::HTTP_OK`  karena secara default sudah 200

2021-03-30 04:52 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    public function update(CommandCenterShiftUpdateRequest $request, CommandCenterShift $commandCenterShift)
kang ini sudah saya perbaiki, apakah sudah tepat kang @ayocodingit ? https://github.com/jabardigitalservice/reservasi-backend/pull/90/commits/07a1f56b1d6a48581448a22af8d8396acf4baec3

2021-03-30 05:05 UTC, ayocodingit commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    public function update(CommandCenterShiftUpdateRequest $request, CommandCenterShift $commandCenterShift)
minor dikit yah kang @iprasetyaa sama nama form request nya ganti kang lebih global

2021-03-30 06:13 UTC, rindibudiaramdhan approved these changes

2021-03-30 06:23 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    public function update(CommandCenterShiftUpdateRequest $request, CommandCenterShift $commandCenterShift)
Woke kang @ayocodingit

2021-03-30 06:30 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +    public function update(CommandCenterShiftUpdateRequest $request, CommandCenterShift $commandCenterShift)
done ya kang https://github.com/jabardigitalservice/reservasi-backend/pull/90/commits/04f3a8cce3589d1f37a5d96129ad99f1cc34b7da

2021-03-30 06:30 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +        return response()->json(['message' => 'deleted'], Response::HTTP_OK);
Oke kang, biar jelas aja tadinya 😅

2021-03-30 06:32 UTC, iprasetyaa commented on app/Http/Controllers/V1/CommandCenterShiftController.php
> +        return response()->json(['message' => 'deleted'], Response::HTTP_OK);
Kang ini sudah dirubah disini https://github.com/jabardigitalservice/reservasi-backend/pull/90/commits/e6c25897a7ffd604665930fc7822cf85ca499928

2021-03-30 06:35 UTC, iprasetyaa commented
> bisa langsung gini aja kang @iprasetyaa
> `$this->commandCenterShift`
> 
> `commandCenterShift` itu didapat dari route binding model di function update

Kang ini sudah dibuat lebih simple https://github.com/jabardigitalservice/reservasi-backend/pull/90/commits/77a89b5e12dc2ca697fea8ec3db911c31f0b380e

2021-03-30 06:58 UTC, ayocodingit approved these changes
sip good job kang @iprasetyaa

2021-03-30 07:36 UTC, merged