Recaptcha validation for ComCen public reservation
jabardigitalservice/reservasi-backend pull request #98
Opened 2021-04-01 10:16 UTC by samudra-ajri

Add google recaptcha validation method to create and show the reservation.

@jabardigitalservice/jds-backend

2021-04-01 11:47 UTC, ayocodingit commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
>          $recaptcha = new GoogleRecaptcha(['token' => $recaptchaToken]);
masih kurang tepat penggunaan service container nya kang @samudra-ajri
gpp sambil belajar :+1:

2021-04-01 11:49 UTC, ayocodingit commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +    public function recaptchaValidation($request)
berarti penggunaaan GoogleRecaptcha dibuat reusable yah ?

2021-04-04 16:15 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
>          $recaptcha = new GoogleRecaptcha(['token' => $recaptchaToken]);
Punten, Kang..
Resolving service container-nya sudah diperbaiki.

Punten koreksinya, Kang.
Hatur nuhun

d493608

2021-04-04 16:17 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +    public function recaptchaValidation($request)
Instance service providernya sudah dimodifikasi, Kang..
Boleh koreksinya?

Hatur nuhun
d493608

2021-04-05 00:35 UTC, ayocodingit approved these changes

2021-04-05 00:35 UTC, ayocodingit commented on app/Providers/AppServiceProvider.php
> +        $this->app->bind(GoogleRecaptcha::class, function ($app, $params) {
Kang @samudra-ajri kalau gak salah artikel yang aku share kapan menggunakan singleton dan bind itu ?

https://laracasts.com/discuss/channels/general-discussion/bind-vs-singleton-when-and-what-to-choose

2021-04-05 00:35 UTC, ayocodingit commented on app/Recaptchas/GoogleRecaptcha.php
> +    protected $response;
Ini bisa di hapus yah kang @samudra-ajri soalnya gak digunakan

2021-04-05 00:35 UTC, ayocodingit commented on app/Recaptchas/GoogleRecaptcha.php
> +        $response = json_decode($response->getBody(), true);
Kalau gak salah kemaren untuk dapatkan response success TRUE atau FALSE harus get content juga yah atau cukup gini aja kang @samudra-ajri

2021-04-05 00:35 UTC, ayocodingit requested changes
Minor kang

2021-04-05 01:39 UTC, yohang88 requested changes
Validasi agar sesuai konteks

2021-04-05 01:39 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +        App::makeWith(GoogleRecaptcha::class, ['request' => $request]);
@samudra-ajri @iprasetyaa Validasi Recaptcha, sesuai namanya adalah berfungsi untuk validasi. Maka konteks yang lebih tepat adalah proses validasi dilakukan di Form Request 😁 

Kurangi penggunaan `abort_if()` karena helper ini terlalu kasar memaksa 😂

2021-04-05 01:50 UTC, ayocodingit commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +        App::makeWith(GoogleRecaptcha::class, ['request' => $request]);
Mau nanya mas kalau di simpen di form request itu di simpen di authorized nya atau menggunakan after hehe 😁😁

2021-04-05 01:51 UTC, samudra-ajri commented on app/Providers/AppServiceProvider.php
> +        $this->app->bind(GoogleRecaptcha::class, function ($app, $params) {
Siap, Kang.. sudah saya pelajari, yg lebih tepat dipakai adalah bind

2021-04-05 01:52 UTC, samudra-ajri commented on app/Recaptchas/GoogleRecaptcha.php
> +        $response = json_decode($response->getBody(), true);
Betul, Kang..
Pakai getBody() sudah cukup

2021-04-05 01:55 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +        App::makeWith(GoogleRecaptcha::class, ['request' => $request]);
Baik, Mas Yoga, Kang Firman..
Saya coba pelajari dahulu.

Hatur nuhun..

2021-04-05 02:14 UTC, yohang88 commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +        App::makeWith(GoogleRecaptcha::class, ['request' => $request]);
@ayocodingit bisa dibuat custom Validation Rule kan 😀 Jadi proses validasi recaptcha ini di custom validation rule. Sehingga bisa reusable juga dipakai di tempat lain.

2021-04-05 02:40 UTC, samudra-ajri commented on app/Recaptchas/GoogleRecaptcha.php
> +    protected $response;
Siap, Kang

2021-04-05 06:47 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +        App::makeWith(GoogleRecaptcha::class, ['request' => $request]);
Siap, Mas Yoga.
Boleh koreksinya?

Hatur nuhun
ff095af

2021-04-05 09:11 UTC, ayocodingit commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +        App::makeWith(GoogleRecaptcha::class, ['request' => $request]);
wah ilmu baru menggunakan prepareForValidation
![image](https://user-images.githubusercontent.com/41193120/113558258-868ac900-9629-11eb-96bc-ac1ebe7f43d0.png)
:+1:

2021-04-05 09:12 UTC, ayocodingit commented on app/Recaptchas/GoogleRecaptcha.php
> +use stdClass;
ini bisa di hapus yah kang @samudra-ajri

2021-04-05 09:56 UTC, yohang88 approved these changes
Mantaaps @samudra-ajri @iprasetyaa @ayocodingit 👍 

Minor aja dari saya ya. Kalau sudah diperbaiki, bisa dilanjut approval+mergenya.

2021-04-05 09:56 UTC, yohang88 commented on app/Rules/GoogelRecaptchaRule.php
> +        return $this->recaptcha->response['error-codes'][0];
Minor saja. Pesan validasi recaptcha sebaiknya jangan lempar response dari google (karena bisa saja ada info yang sensitif). Cukup beri pesan error ke frontend, "Recaptcha tidak valid."

2021-04-05 10:03 UTC, samudra-ajri commented on app/Rules/GoogelRecaptchaRule.php
> +        return $this->recaptcha->response['error-codes'][0];
Siap, Mas.. 86, Mas..
hatur nuhun

2021-04-05 10:03 UTC, samudra-ajri commented on app/Recaptchas/GoogleRecaptcha.php
> +use stdClass;
Siap, 86, Kang..

2021-04-05 10:19 UTC, samudra-ajri commented on app/Http/Controllers/V1/CommandCenterReservationPublicController.php
> +        App::makeWith(GoogleRecaptcha::class, ['request' => $request]);
Semoga penggunaannya tepat, Kang.. haha

2021-04-05 10:24 UTC, ayocodingit approved these changes

2021-04-06 01:50 UTC, merged